{{- if .Values.envoyGateway.clientTrafficPolicy.enabled -}}
{{- $fullName := include "gateway-api.fullname" . -}}
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: ClientTrafficPolicy
metadata:
  name: {{ default $fullName .Values.envoyGateway.clientTrafficPolicy.name }}
  namespace: {{ include "gateway-api.namespace" . }}
  labels:
    {{- include "gateway-api.labels" . | nindent 4 }}
    {{- with .Values.envoyGateway.clientTrafficPolicy.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.envoyGateway.clientTrafficPolicy.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.envoyGateway.clientTrafficPolicy.spec }}
  {{- tpl (. | toYaml) $ | nindent 2 }}
  {{- end }}
{{- end }}
