{{- if .Values.envoyGateway.securityPolicy.enabled -}}
{{- $fullName := include "gateway-api.fullname" . -}}
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: {{ .Values.envoyGateway.securityPolicy.nameOverride | default (printf "%s-%s" $fullName (.Values.envoyGateway.securityPolicy.name | default "")) | trunc 63 | trimSuffix "-" }}
  namespace: {{ include "gateway-api.namespace" . }}
  labels:
    {{- include "gateway-api.labels" . | nindent 4 }}
    {{- with .Values.envoyGateway.securityPolicy.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.envoyGateway.securityPolicy.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.envoyGateway.securityPolicy.spec }}
  {{- tpl (. | toYaml) $ | nindent 2 }}
  {{- end }}
{{- end }}
