{{- with .Values.cassandra.dbUser.existingSecret }}
{{- if and .name .sealedPassword -}}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "common.markerLabels" $ | nindent 4 }}
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
spec:
  template:
    type: Opaque
  encryptedData:
    password: {{ .sealedPassword | quote }}
{{- end }}
{{- end }}