## Default values for common-tpls.
## This is a YAML-formatted file.
## Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

namespaceOverride: ""

rewriteLabels: {}
  ## Overwrites the value of the recommended labels starting with app.kubernetes.io/*
  # environment: "staging"
  # instance: ""
  # component: ""
  # partOf: ""

additionalLabels: {}
  ## This will extend the recommended labels starting with app.kubernetes.io/*
  # metadata.organization/name: "Example ltd."
  # metadata.organization/manager: "john.doe@example.com"

customLabels: {}
  ## This will replace the recommended labels with the following.
  ## All these labels are also used in the selector.
  # selector:
  #   app: web-app
  #   instance: web-app-api-dev
  # others:
  #   component: api
  #   version: "1.1.0"
  #   environment: dev
  #   tier: frontend
