{
 "title": "Spring Boot / Overview",
 "tags": [
  "spring-boot",
  "actuator"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(process_uptime_seconds, namespace)"
    }
   },
   {
    "name": "service",
    "label": "Service",
    "query": {
     "query": "label_values(process_uptime_seconds{namespace=\"$namespace\"}, service)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(process_uptime_seconds{service=\"$service\"}, pod)"
    }
   },
   {
    "name": "hikaricp",
    "label": "HikariCP-Pool",
    "query": {
     "query": "label_values(hikaricp_connections{pod=~\"$pod\", service=~\"$service\"}, pool)"
    }
   },
   {
    "name": "memory_pool_heap",
    "label": "Memory Pool (heap)",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{service=~\"$service\", pod=~\"$pod\", area=\"heap\"},id)"
    }
   },
   {
    "name": "memory_pool_nonheap",
    "label": "Memory Pool (nonheap)",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{service=~\"$service\", pod=~\"$pod\", area=\"nonheap\"},id)"
    }
   },
   {
    "name": "retry_name",
    "label": "Retry Name",
    "query": {
     "query": "label_values(resilience4j_retry_calls_total{service=~\"$service\", pod=~\"$pod\"}, name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Basic Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(process_uptime_seconds{service=~\"$service\", pod=~\"$pod\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Heap Used",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{service=~\"$service\", pod=~\"$pod\", area=\"heap\"})*100/sum(jvm_memory_max_bytes{service=~\"$service\",pod=~\"$pod\", area=\"heap\"})"
    }
   ]
  },
  {
   "title": "Non-Heap Used",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{service=~\"$service\", pod=~\"$pod\", area=\"nonheap\"})*100/sum(jvm_memory_max_bytes{service=~\"$service\",pod=~\"$pod\", area=\"nonheap\"})"
    }
   ]
  },
  {
   "title": "Start time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(process_start_time_seconds{service=~\"$service\", pod=~\"$pod\"}*1000)"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{service=~\"$service\", uri!=\".*actuator.*\"}[$__range])) - (5 * sum(increase(http_server_requests_seconds_count{service=~\"$service\", uri!=\".*actuator.*\"}[$__range])) / 100)"
    }
   ]
  },
  {
   "title": "Success Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{service=~\"$service\", uri!=\".*actuator.*\", status=~\"2.*\"}[$__range])) - ((5 * (sum(increase(http_server_requests_seconds_count{service=~\"$service\", uri!=\".*actuator.*\", status=~\"2.*\"}[$__range])))) / 100)"
    }
   ]
  },
  {
   "title": "Status Code HTTP Request",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{service=~\"$service\", uri!=\".*actuator.*\", status=\"200\"}[$__range])) - (5 * sum(increase(http_server_requests_seconds_count{service=~\"$service\", uri!=\".*actuator.*\", status=\"200\"}[$__range])) / 100)",
     "legendFormat": "200"
    },
    {
     "expr": "sum(increase(http_server_requests_seconds_count{service=~\"$service\", uri!=\".*actuator.*\", status=\"201\"}[$__range])) - (5 * sum(increase(http_server_requests_seconds_count{service=~\"$service\", uri!=\".*actuator.*\", status=\"201\"}[$__range])) / 100)",
     "legendFormat": "201"
    },
    {
     "expr": "sum(increase(http_server_requests_seconds_count{service=~\"$service\", uri!=\".*actuator.*\", status=\"202\"}[$__range])) - (5 * sum(increase(http_server_requests_seconds_count{service=~\"$service\", uri!=\".*actuator.*\", status=\"202\"}[$__range])) / 100)",
     "legendFormat": "202"
    },
    {
     "expr": "sum(increase(http_server_requests_seconds_count{service=~\"$service\", uri!=\".*actuator.*\", status=\"204\"}[$__range])) - (5 * sum(increase(http_server_requests_seconds_count{service=~\"$service\", uri!=\".*actuator.*\", status=\"204\"}[$__range])) / 100)",
     "legendFormat": "204"
    },
    {
     "expr": "sum(increase(http_server_requests_seconds_count{service=~\"$service\", uri!=\".*actuator.*\", status=\"400\"}[$__range])) - (5 * sum(increase(http_server_requests_seconds_count{service=~\"$service\", uri!=\".*actuator.*\", status=\"400\"}[$__range])) / 100)",
     "legendFormat": "400"
    },
    {
     "expr": "sum(increase(http_server_requests_seconds_count{service=~\"$service\", uri!=\".*actuator.*\", status=\"401\"}[$__range])) - (5 * sum(increase(http_server_requests_seconds_count{service=~\"$service\", uri!=\".*actuator.*\", status=\"401\"}[$__range])) / 100)",
     "legendFormat": "401"
    },
    {
     "expr": "sum(increase(http_server_requests_seconds_count{service=~\"$service\", uri!=\".*actuator.*\", status=\"403\"}[$__range])) - (5 * sum(increase(http_server_requests_seconds_count{service=~\"$service\", uri!=\".*actuator.*\", status=\"403\"}[$__range])) / 100)",
     "legendFormat": "403"
    },
    {
     "expr": "sum(increase(http_server_requests_seconds_count{service=~\"$service\", uri!=\".*actuator.*\", status=\"409\"}[$__range])) - (5 * sum(increase(http_server_requests_seconds_count{service=~\"$service\", uri!=\".*actuator.*\", status=\"409\"}[$__range])) / 100)",
     "legendFormat": "409"
    },
    {
     "expr": "sum(increase(http_server_requests_seconds_count{service=~\"$service\", uri!=\".*actuator.*\", status=\"408\"}[$__range])) - (5 * sum(increase(http_server_requests_seconds_count{service=~\"$service\", uri!=\".*actuator.*\", status=\"408\"}[$__range])) / 100)",
     "legendFormat": "408"
    },
    {
     "expr": "sum(increase(http_server_requests_seconds_count{service=~\"$service\", uri!=\".*actuator.*\", status=\"404\"}[$__range])) - (5 * sum(increase(http_server_requests_seconds_count{service=~\"$service\", uri!=\".*actuator.*\", status=\"404\"}[$__range])) / 100)",
     "legendFormat": "404"
    },
    {
     "expr": "sum(increase(http_server_requests_seconds_count{service=~\"$service\", uri!=\".*actuator.*\", status=\"500\"}[$__range])) - (5 * sum(increase(http_server_requests_seconds_count{service=~\"$service\", uri!=\".*actuator.*\", status=\"500\"}[$__range])) / 100)",
     "legendFormat": "500"
    },
    {
     "expr": "sum(increase(http_server_requests_seconds_count{service=~\"$service\", uri!=\".*actuator.*\", status=\"502\"}[$__range])) - (5 * sum(increase(http_server_requests_seconds_count{service=~\"$service\", uri!=\".*actuator.*\", status=\"502\"}[$__range])) / 100)",
     "legendFormat": "502"
    },
    {
     "expr": "sum(increase(http_server_requests_seconds_count{service=~\"$service\", uri!=\".*actuator.*\", status=\"503\"}[$__range])) - (5 * sum(increase(http_server_requests_seconds_count{service=~\"$service\", uri!=\".*actuator.*\", status=\"503\"}[$__range])) / 100)",
     "legendFormat": "503"
    },
    {
     "expr": "sum(increase(http_server_requests_seconds_count{service=~\"$service\", uri!=\".*actuator.*\", status=\"504\"}[$__range])) - (5 * sum(increase(http_server_requests_seconds_count{service=~\"$service\", uri!=\".*actuator.*\", status=\"504\"}[$__range])) / 100)",
     "legendFormat": "504"
    }
   ]
  },
  {
   "title": "Failed Requests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{service=~\"$service\", uri!=\".*actuator.*\", status=~\"5.*\"}[$__range])) - (5 * sum(increase(http_server_requests_seconds_count{service=~\"$service\", uri!=\".*actuator.*\", status=~\"5.*\"}[$__range])) / 100)"
    }
   ]
  },
  {
   "title": "Warning Requests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{service=~\"$service\", uri!=\".*actuator.*\", status=~\"4.*\"}[$__range])) - (5 * sum(increase(http_server_requests_seconds_count{service=~\"$service\", uri!=\".*actuator.*\", status=~\"4.*\"}[$__range])) / 100)"
    }
   ]
  },
  {
   "title": "Req / Sec",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(http_server_requests_seconds_count{service=~\"$service\"}[$__range]))"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "system_cpu_usage{pod=~\"$pod\", service=~\"$service\"}",
     "legendFormat": "System CPU Usage"
    },
    {
     "expr": "process_cpu_usage{pod=~\"$pod\", service=~\"$service\"}",
     "legendFormat": "Process CPU Usage"
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "system_load_average_1m{pod=~\"$pod\", service=~\"$service\"}",
     "legendFormat": "Load Average [1m]"
    },
    {
     "expr": "system_cpu_count{pod=~\"$pod\", service=~\"$service\"}",
     "legendFormat": "CPU Core Size"
    }
   ]
  },
  {
   "title": "HTTP Server Requests Count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "http_server_requests_seconds_count{pod=~\"$pod\", service=~\"$service\"}",
     "legendFormat": "{{method}} [{{status}}] - {{uri}}"
    }
   ]
  },
  {
   "title": "HTTP Server Requests Sum",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 21 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "http_server_requests_seconds_sum{pod=~\"$pod\", service=~\"$service\"}",
     "legendFormat": "{{method}} [{{status}}] - {{uri}}"
    }
   ]
  },
  {
   "title": "HTTP Server Requests Max",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 21 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "http_server_requests_seconds_max{pod=~\"$pod\", service=~\"$service\"}",
     "legendFormat": "{{method}} [{{status}}] - {{uri}}"
    }
   ]
  },
  {
   "title": "JVM Statistics - Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {}
   ]
  },
  {
   "title": "$memory_pool_heap (heap)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 28 },
   "repeat": "memory_pool_heap",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{pod=~\"$pod\", service=~\"$service\", id=\"$memory_pool_heap\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "jvm_memory_committed_bytes{pod=~\"$pod\", service=~\"$service\", id=\"$memory_pool_heap\"}",
     "legendFormat": "Commited"
    },
    {
     "expr": "jvm_memory_max_bytes{pod=~\"$pod\", service=~\"$service\", id=\"$memory_pool_heap\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "$memory_pool_nonheap (non-heap)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 36 },
   "repeat": "memory_pool_nonheap",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{pod=~\"$pod\", service=~\"$service\", id=\"$memory_pool_nonheap\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "jvm_memory_committed_bytes{pod=~\"$pod\", service=~\"$service\", id=\"$memory_pool_nonheap\"}",
     "legendFormat": "Commited"
    },
    {
     "expr": "jvm_memory_max_bytes{pod=~\"$pod\", service=~\"$service\", id=\"$memory_pool_nonheap\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Classes Unloaded",
   "type": "graph",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(jvm_classes_unloaded_total{service=~\"$service\", pod=~\"$pod\"}[5m])",
     "legendFormat": "Classes Unloaded"
    }
   ]
  },
  {
   "title": "Classes Loaded",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "jvm_classes_loaded{pod=~\"$pod\", service=~\"$service\"}",
     "legendFormat": "Classes Loaded"
    }
   ]
  },
  {
   "title": "Mapped Buffers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_buffer_memory_used_bytes{pod=~\"$pod\", service=~\"$service\", id=\"mapped\"}",
     "legendFormat": "Used Bytes"
    },
    {
     "expr": "jvm_buffer_total_capacity_bytes{pod=~\"$pod\", service=~\"$service\", id=\"mapped\"}",
     "legendFormat": "Capacity Bytes"
    }
   ]
  },
  {
   "title": "Memory Allocate/Promote",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "irate(jvm_gc_memory_allocated_bytes_total{pod=~\"$pod\", service=~\"$service\"}[5m])",
     "legendFormat": "allocated"
    },
    {
     "expr": "irate(jvm_gc_memory_promoted_bytes_total{pod=~\"$pod\", service=~\"$service\"}[5m])",
     "legendFormat": "promoted"
    }
   ]
  },
  {
   "title": "Direct Buffers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_buffer_memory_used_bytes{pod=~\"$pod\", service=~\"$service\", id=\"direct\"}",
     "legendFormat": "Used Bytes"
    },
    {
     "expr": "jvm_buffer_total_capacity_bytes{pod=~\"$pod\", service=~\"$service\", id=\"direct\"}",
     "legendFormat": "Capacity Bytes"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_daemon{pod=~\"$pod\", service=~\"$service\"}",
     "legendFormat": "Daemon"
    },
    {
     "expr": "jvm_threads_live{pod=~\"$pod\", service=~\"$service\"}",
     "legendFormat": "Live"
    },
    {
     "expr": "jvm_threads_peak{pod=~\"$pod\", service=~\"$service\"}",
     "legendFormat": "Peak"
    }
   ]
  },
  {
   "title": "JVM Statistics - GC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 },
   "targets": [
    {}
   ]
  },
  {
   "title": "GC Count",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 76 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "irate(jvm_gc_pause_seconds_count{pod=~\"$pod\", service=~\"$service\"}[5m])",
     "legendFormat": "{{action}} [{{cause}}]"
    }
   ]
  },
  {
   "title": "GC Stop the World Duration",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 76 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "irate(jvm_gc_pause_seconds_sum{pod=~\"$pod\", service=~\"$service\"}[5m])",
     "legendFormat": "{{action}} [{{cause}}]"
    }
   ]
  },
  {
   "title": "HikariCP Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 86 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Connections Size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hikaricp_connections{service=~\"$service\", pod=~\"$pod\", pool=\"$hikaricp\"}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 87 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hikaricp_connections_active{pod=~\"$pod\", service=~\"$service\", pool=\"$hikaricp\"}",
     "legendFormat": "Active"
    },
    {
     "expr": "hikaricp_connections_idle{pod=~\"$pod\", service=~\"$service\", pool=\"$hikaricp\"}",
     "legendFormat": "Idle"
    },
    {
     "expr": "hikaricp_connections_pending{pod=~\"$pod\", service=~\"$service\", pool=\"$hikaricp\"}",
     "legendFormat": "Pending"
    }
   ]
  },
  {
   "title": "Connection Timeout Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hikaricp_connections_timeout_total{service=~\"$service\",pod=~\"$pod\", pool=\"$hikaricp\"}"
    }
   ]
  },
  {
   "title": "Connection Creation Time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 95 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "hikaricp_connections_creation_seconds_sum{pod=~\"$pod\", service=~\"$service\", pool=\"$hikaricp\"} / hikaricp_connections_creation_seconds_count{pod=~\"$pod\", service=~\"$service\", pool=\"$hikaricp\"}",
     "legendFormat": "Creation Time"
    }
   ]
  },
  {
   "title": "Connection Usage Time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 95 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "hikaricp_connections_usage_seconds_sum{pod=~\"$pod\", service=~\"$service\", pool=\"$hikaricp\"} / hikaricp_connections_usage_seconds_count{pod=~\"$pod\", service=~\"$service\", pool=\"$hikaricp\"}",
     "legendFormat": "Usage Time"
    }
   ]
  },
  {
   "title": "Connection Acquire Time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 95 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "hikaricp_connections_acquire_seconds_sum{pod=~\"$pod\", service=~\"$service\", pool=\"$hikaricp\"} / hikaricp_connections_acquire_seconds_count{pod=~\"$pod\", service=~\"$service\", pool=\"$hikaricp\"}",
     "legendFormat": "Acquire Time"
    }
   ]
  },
  {
   "title": "Hibernate Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 101 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total Transactions",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(hibernate_transactions_total{service=~\"$service\", result=\"success\"})"
    }
   ]
  },
  {
   "title": "Prepared Statements ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(hibernate_statements_total{service=~\"$service\", pod=~\"$pod\", status=\"prepared\"})",
     "legendFormat": "Statements"
    }
   ]
  },
  {
   "title": "Total optimistic locking failures",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(hibernate_optimistic_failures_total{service=~\"$service\",entityManagerFactory=\"entityManagerFactory\"})"
    }
   ]
  },
  {
   "title": "Total query executions",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(hibernate_query_executions_total{service=~\"$service\",entityManagerFactory=\"entityManagerFactory\"})"
    }
   ]
  },
  {
   "title": "Entity Manager / Session Metrics",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 105 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(hibernate_sessions_open_total{service=~\"$service\", pod=~\"$pod\"}[5m])  ",
     "legendFormat": "sessions_opened"
    },
    {
     "expr": "rate(hibernate_sessions_closed_total{service=~\"$service\", pod=~\"$pod\"}[5m])  ",
     "legendFormat": "sessions_closed"
    },
    {
     "expr": "rate(hibernate_flushes_total{service=~\"$service\", pod=~\"$pod\"}[5m])  ",
     "legendFormat": "flushes"
    }
   ]
  },
  {
   "title": "Entity Collection Metrics",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 105 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(hibernate_collections_loads_total{service=~\"$service\", pod=~\"$pod\"}[2m])",
     "legendFormat": "collections loaded"
    },
    {
     "expr": "rate(hibernate_collections_updates_total{service=~\"$service\", pod=~\"$pod\"}[2m])",
     "legendFormat": "collections updated"
    },
    {
     "expr": "rate(hibernate_collections_fetches_total{service=~\"$service\", pod=~\"$pod\"}[2m])",
     "legendFormat": "collection fetches"
    },
    {
     "expr": "rate(hibernate_collections_deletes_total{service=~\"$service\", pod=~\"$pod\"}[2m])",
     "legendFormat": "remove"
    },
    {
     "expr": "rate(hibernate_collections_recreates_total{service=~\"$service\", pod=~\"$pod\"}[2m])",
     "legendFormat": "recreates"
    }
   ]
  },
  {
   "title": "Entity Metrics",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 113 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(hibernate_collections_loads_total{service=~\"$service\", pod=~\"$pod\"}[2m])",
     "legendFormat": "entities loaded"
    },
    {
     "expr": "rate(hibernate_entities_updates_total{service=~\"$service\", pod=~\"$pod\"}[2m])",
     "legendFormat": "entities updated"
    },
    {
     "expr": "rate(hibernate_entities_fetches_total{service=~\"$service\", pod=~\"$pod\"}[2m])",
     "legendFormat": "entities fetched"
    },
    {
     "expr": "rate(hibernate_entities_deletes_total{service=~\"$service\", pod=~\"$pod\"}[2m])",
     "legendFormat": "entities removed"
    },
    {
     "expr": "rate(hibernate_entities_recreates_total{service=~\"$service\", pod=~\"$pod\"}[2m])",
     "legendFormat": "recreates"
    },
    {
     "expr": "rate(hibernate_entities_inserts_total{service=~\"$service\", pod=~\"$pod\"}[2m])",
     "legendFormat": "entities inserted"
    }
   ]
  },
  { "title": "Resilience4j Retry", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 121 } },
  {
   "title": "Rate retryable calls: $retry_name",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 122 },
   "yaxes": [
    { "format": "short", "label": "Number of calls" }
   ],
   "targets": [
    {
     "expr": "rate(resilience4j_retry_calls_total{application=~\"$application\",name=~\"$retry_name\",}[1m])",
     "legendFormat": "{{ kind }}"
    }
   ]
  },
  {
   "title": "HTTP Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 130 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Request Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 131 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(http_server_requests_seconds_count{pod=~\"$pod\", service=~\"$service\", uri!~\".*actuator.*\"}[5m])",
     "legendFormat": "{{method}} [{{status}}] - {{uri}}"
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 138 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "irate(http_server_requests_seconds_sum{pod=~\"$pod\", service=~\"$service\", exception=\"None\", uri!~\".*actuator.*\"}[5m]) / irate(http_server_requests_seconds_count{pod=~\"$pod\", service=~\"$service\", exception=\"None\", uri!~\".*actuator.*\"}[5m])",
     "legendFormat": "{{method}} [{{status}}] - {{uri}}"
    }
   ]
  },
  {
   "title": "Logback Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 145 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Log Event (1m)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 146 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(logback_events_total{service=~\"$service\", pod=~\"$pod\"}[1m])",
     "legendFormat": "{{level}}"
    }
   ]
  }
 ]
}