{{- range (index .Values "cert-manager" "clusterIssuer") }}
{{- range .additioinalSecrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    app: {{ template "cert-manager.name" $ }}
    app.kubernetes.io/name: {{ template "cert-manager.name" $ }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/component: "issuer"
    {{- include "labels" $ | nindent 4 }}
  {{- if or $.Values.deploymentAnnotations .annotations }}
  annotations:
  {{- with $.Values.deploymentAnnotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
type: {{ default "Opaque" .type }}
stringData:
{{- range $key, $value := .stringData -}}
  {{ $key | nindent 2 }}: {{ $value | quote }}
{{- end -}}
{{- end }}
{{- end }}