{
 "title": "Memcached",
 "description": "Memcached dashboard for grafana 6.5.1 or above.\r\nDataSource: Prometheus\r\nCollector: Memcached official exporter : https://github.com/prometheus/memcached_exporter/releases \r\n",
 "tags": [ "memcached" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(memcached_up,namespace)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(memcached_up{namespace=\"$namespace\"},pod)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(memcached_up{namespace=\"$namespace\", pod=\"$pod\"},instance)"
    }
   },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(memcached_up{namespace=\"$namespace\"},job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Instance State",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "memcached_up{pod=\"$pod\",instance=~\"$instance\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Up Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "memcached_uptime_seconds{pod=\"$pod\",instance=~\"$instance\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "memcached_current_bytes{pod=\"$pod\",instance=~\"$instance\",job=\"$job\"}/memcached_limit_bytes{pod=\"$pod\",instance=~\"$instance\",job=\"$job\"}",
     "legendFormat": "Memory used",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Get & Set ratio",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(memcached_commands_total{pod=\"$pod\",instance=~\"$instance\",job=\"$job\",command=\"get\"}) / (sum(memcached_commands_total{pod=\"$pod\",instance=~\"$instance\",job=\"$job\",command=\"get\"}) + sum(memcached_commands_total{pod=\"$pod\",instance=~\"$instance\",job=\"$job\",command=\"get\"}))",
     "legendFormat": "Get"
    },
    {
     "expr": "sum(memcached_commands_total{pod=\"$pod\",instance=~\"$instance\",job=\"$job\",command=\"set\"}) / (sum(memcached_commands_total{pod=\"$pod\",instance=~\"$instance\",job=\"$job\",command=\"set\"}) + sum(memcached_commands_total{pod=\"$pod\",instance=~\"$instance\",job=\"$job\",command=\"set\"}))",
     "legendFormat": "Set"
    }
   ]
  },
  {
   "title": "Hit & Miss ratio",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(memcached_commands_total{pod=\"$pod\",instance=~\"$instance\",job=\"$job\",command=\"get\",status=\"hit\"}) / sum(memcached_commands_total{pod=\"$pod\",instance=~\"$instance\",job=\"$job\",command=\"get\"})",
     "legendFormat": "hit"
    },
    {
     "expr": "sum(memcached_commands_total{pod=\"$pod\",instance=~\"$instance\",job=\"$job\",command=\"get\",status=\"miss\"}) / sum(memcached_commands_total{pod=\"$pod\",instance=~\"$instance\",job=\"$job\",command=\"get\"})",
     "legendFormat": "miss"
    }
   ]
  },
  {
   "title": "Evicts (total)",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (memcached_items_evicted_total{pod=\"$pod\",instance=~\"$instance\",job=\"$job\"})"
    }
   ]
  },
  {
   "title": "Reclaims (total)",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (memcached_items_reclaimed_total{pod=\"$pod\",instance=~\"$instance\",job=\"$job\"})"
    }
   ]
  },
  {
   "title": "Evicts & Reclaims rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (irate (memcached_items_evicted_total{pod=\"$pod\",instance=~\"$instance\",job=\"$job\"}[5m]))",
     "legendFormat": "evicts"
    },
    {
     "expr": "sum (irate (memcached_items_reclaimed_total{pod=\"$pod\",instance=~\"$instance\",job=\"$job\"}[5m]))",
     "legendFormat": "reclaims"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "memcached_current_connections{pod=\"$pod\",instance=~\"$instance\",job=\"$job\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Hit rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(irate (memcached_commands_total{pod=\"$pod\",instance=~\"$instance\",job=\"$job\",command=\"get\",status=\"hit\"}[5m])) / sum(irate (memcached_commands_total{pod=\"$pod\",instance=~\"$instance\",job=\"$job\",command=\"get\"}[5m]\n))",
     "legendFormat": "Hit"
    }
   ]
  },
  {
   "title": "Read/Write",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "delta(memcached_read_bytes_total{pod=\"$pod\",instance=~\"$instance\",job=\"$job\"}[1m])",
     "legendFormat": "read"
    },
    {
     "expr": "delta(memcached_written_bytes_total{pod=\"$pod\",instance=~\"$instance\",job=\"$job\"}[1m])",
     "legendFormat": "write"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "memcached_current_bytes{pod=\"$pod\",instance=~\"$instance\",job=\"$job\"}/memcached_limit_bytes{pod=\"$pod\",instance=~\"$instance\",job=\"$job\"}",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "Items in cache",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "memcached_current_items{pod=\"$pod\",instance=~\"$instance\",job=\"$job\"}",
     "legendFormat": "Items"
    }
   ]
  },
  {
   "title": "Commands",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(memcached_commands_total{pod=\"$pod\",instance=~\"$instance\",job=\"$job\"}[1m])) by (command)",
     "legendFormat": "{{command}}"
    }
   ]
  },
  {
   "title": "QPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(delta(memcached_commands_total{pod=\"$pod\",instance=~\"$instance\",job=\"$job\"}[1m]))/60",
     "legendFormat": "QPS"
    }
   ]
  },
  {
   "title": "Hit Ratio",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(delta(memcached_commands_total{pod=\"$pod\",instance=~\"$instance\",job=\"$job\", status=\"hit\"}[1m]))  / sum(delta(memcached_commands_total{pod=\"$pod\",instance=~\"$instance\",job=\"$job\"}[1m])) * 100",
     "legendFormat": "Hit Ratio"
    }
   ]
  },
  {
   "title": "Hit Ratio Per Command",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(delta(memcached_commands_total{pod=\"$pod\",instance=~\"$instance\",job=\"$job\",command=\"cas\",status=\"hit\"}[1m])) / sum(delta(memcached_commands_total{pod=\"$pod\",instance=~\"$instance\",job=\"$job\",command=\"cas\"}[1m])) * 100",
     "legendFormat": "cas"
    },
    {
     "expr": "sum(delta(memcached_commands_total{pod=\"$pod\",instance=~\"$instance\",job=\"$job\",command=\"decr\",status=\"hit\"}[1m])) / sum(delta(memcached_commands_total{pod=\"$pod\",instance=~\"$instance\",job=\"$job\",command=\"decr\"}[1m])) * 100",
     "legendFormat": "decr"
    },
    {
     "expr": "sum(delta(memcached_commands_total{pod=\"$pod\",instance=~\"$instance\",job=\"$job\",command=\"delete\",status=\"hit\"}[1m])) / sum(delta(memcached_commands_total{pod=\"$pod\",instance=~\"$instance\",job=\"$job\",command=\"delete\"}[1m])) * 100",
     "legendFormat": "delete"
    },
    {
     "expr": "sum(delta(memcached_commands_total{pod=\"$pod\",instance=~\"$instance\",job=\"$job\",command=\"flush\",status=\"hit\"}[1m])) / sum(delta(memcached_commands_total{pod=\"$pod\",instance=~\"$instance\",job=\"$job\",command=\"flush\"}[1m])) * 100",
     "legendFormat": "flush"
    },
    {
     "expr": "sum(delta(memcached_commands_total{pod=\"$pod\",instance=~\"$instance\",job=\"$job\",command=\"get\",status=\"hit\"}[1m])) / sum(delta(memcached_commands_total{pod=\"$pod\",instance=~\"$instance\",job=\"$job\",command=\"get\"}[1m])) * 100",
     "legendFormat": "get"
    },
    {
     "expr": "sum(delta(memcached_commands_total{pod=\"$pod\",instance=~\"$instance\",job=\"$job\",command=\"incr\",status=\"hit\"}[1m])) / sum(delta(memcached_commands_total{pod=\"$pod\",instance=~\"$instance\",job=\"$job\",command=\"incr\"}[1m])) * 100",
     "legendFormat": "incr"
    },
    {
     "expr": "sum(delta(memcached_commands_total{pod=\"$pod\",instance=~\"$instance\",job=\"$job\",command=\"set\",status=\"hit\"}[1m])) / sum(delta(memcached_commands_total{pod=\"$pod\",instance=~\"$instance\",job=\"$job\",command=\"set\"}[1m])) * 100",
     "legendFormat": "set"
    },
    {
     "expr": "sum(delta(memcached_commands_total{pod=\"$pod\",instance=~\"$instance\",job=\"$job\",command=\"touch\",status=\"hit\"}[1m])) / sum(delta(memcached_commands_total{pod=\"$pod\",instance=~\"$instance\",job=\"$job\",command=\"touch\"}[1m])) * 100",
     "legendFormat": "touch"
    }
   ]
  }
 ]
}