{{- if .Values.ingress.enabled -}}
{{- $deploymentName := include "common.deployment.name" . -}}
{{- $namespace := include "common.namespace" . -}}
{{- $sessionAnnotations := dict "nginx.ingress.kubernetes.io/affinity" "cookie" "nginx.ingress.kubernetes.io/session-cookie-expires" "172800" "nginx.ingress.kubernetes.io/session-cookie-max-age" "172800" -}}
{{- $svcPort := .Values.service.portNumber -}}
{{- if and .Values.ingress.className (not (semverCompare ">=1.18-0" (default $.Capabilities.KubeVersion.GitVersion $.Values.kubeVersionOverride))) }}
  {{- if not (hasKey .Values.ingress.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set .Values.ingress.annotations "kubernetes.io/ingress.class" .Values.ingress.className }}
  {{- end }}
{{- end }}
{{- if semverCompare ">=1.19-0" (default $.Capabilities.KubeVersion.GitVersion $.Values.kubeVersionOverride) -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" (default $.Capabilities.KubeVersion.GitVersion $.Values.kubeVersionOverride) -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $deploymentName }}
  namespace: {{ $namespace }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
  {{- with (mergeOverwrite (.Values.deploymentStrategy.canary.enabled | ternary $sessionAnnotations dict) .Values.ingress.annotations) }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- with .Values.ingress }}
spec:
  {{- if and .className (semverCompare ">=1.18-0" (default $.Capabilities.KubeVersion.GitVersion $.Values.kubeVersionOverride)) }}
  ingressClassName: {{ .className }}
  {{- end }}
  {{- if .tls }}
  tls:
    {{- range .tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ default (include "common.tls.secretName" $) .secretName  }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            {{- if semverCompare ">=1.18-0" (default $.Capabilities.KubeVersion.GitVersion $.Values.kubeVersionOverride) }}
            pathType: {{ default "ImplementationSpecific" .pathType }}
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" (default $.Capabilities.KubeVersion.GitVersion $.Values.kubeVersionOverride) }}
              service:
                name: {{ default $deploymentName .serviceName }}
                port:
                  number: {{ default $svcPort .servicePort }}
              {{- else }}
              serviceName: {{ default $deploymentName .serviceName }}
              servicePort: {{ default $svcPort .servicePort }}
              {{- end }}
          {{- end }}
    {{- end }}
{{- end }}
{{- end }}