{{- if .Values.ingress.enabled -}}
{{- $fullName := include "common.fullname" . -}}
{{- $namespace := include "common.namespace" . -}}
{{- $svcPort := .Values.service.portNumber -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  namespace: {{ $namespace }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- with .Values.ingress }}
spec:
  {{- if .tls.enabled }}
  tls:
    - hosts:
        - {{ .host | quote }}
      secretName: {{ include "common.tls.secretName" $ }}
  {{- end }}
  rules:
    - host: {{ .host | quote }}
      http:
        paths:
          {{- if .paths }}
          {{- range .paths }}
          - path: {{ .path }}
            backend:
              serviceName: {{ .serviceName }}
              servicePort: {{ .servicePort }}
          {{- end }}
          {{- else }}
          - path: /
            backend:
              serviceName: {{ $fullName }}
              servicePort: {{ $svcPort }}
          {{- end }}
{{- end }}
{{- end }}