{{ if and (gt (.Values.replicaCount | int) 1) (or .Values.statelessApp .Values.statefulApp) }}
{{- if semverCompare ">=1.21-0" (default $.Capabilities.KubeVersion.GitVersion $.Values.kubeVersionOverride) -}}
apiVersion: policy/v1
{{- else -}}
apiVersion: policy/v1beta1
{{- end }}
kind: PodDisruptionBudget
metadata:
  name: {{ include "common.fullname" . }}-pdb
  namespace: {{ include "common.namespace" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "common.selectorLabels" . | nindent 6 }}
  {{- with .Values.pdb }}
  {{ toYaml . }}
  {{- end }}
{{ end }}
