{{- if and .Values.metrics.enabled .Values.metrics.prometheusRule.create }}
{{- $labels := mergeOverwrite (include "common.labels" $ | fromYaml) (dict "app.kubernetes.io/component" "metrics") }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "common.fullname" $ }}
  namespace: {{ default .namespace (include "common.namespace" $) }}
  labels:
    {{- $labels | toYaml | nindent 4 }}
spec:
  groups:
  - name: {{ include "common.fullname" $ }}
    rules: {{- tpl (toYaml .Values.metrics.prometheusRule.rules) . | nindent 4  }}
{{- end }}