{{- if .Values.rbac.rules }}
{{- if .Values.rbac.isClusterRole }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ printf "%s-%s" (include "common.fullname" .) .Values.rbac.roleName }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
rules:
{{ toYaml .Values.rbac.rules | indent 2 }}

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ printf "%s-%s" (include "common.fullname" .) .Values.rbac.roleName }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
roleRef:
  apiGroup: {{ .Values.rbac.apiGroup | quote }}
  kind: ClusterRole
  name: {{ printf "%s-%s" (include "common.fullname" .) .Values.rbac.roleName }}
subjects:
  - apiGroup: {{ .Values.rbac.apiGroup }}
    kind: ServiceAccount
    name: {{ include "common.serviceAccountName" . }}
    namespace: {{ include "common.namespace" . }}

{{- else }}

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ printf "%s-%s" (include "common.fullname" .) .Values.rbac.roleName }}
  namespace: {{ include "common.namespace" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
rules:
{{ toYaml .Values.rbac.rules | indent 2 }}

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ printf "%s-%s" (include "common.fullname" .) .Values.rbac.roleName }}
  namespace: {{ include "common.namespace" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
roleRef:
  apiGroup: {{ .Values.rbac.apiGroup | quote }}
  kind: Role
  name: {{ printf "%s-%s" (include "common.fullname" .) .Values.rbac.roleName }}
subjects:
  - apiGroup: {{ .Values.rbac.apiGroup }}
    kind: ServiceAccount
    name: {{ include "common.serviceAccountName" . }}
    namespace: {{ include "common.namespace" . }}
{{- end }}
{{- end }}