{{- if or (and .Values.envFrom.sealedSecret (not .Values.envFrom.useGlobal)) (and $.Values.global.envFrom.sealedSecret .Values.envFrom.createGlobal) }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ include "common.envFrom.sealedSecretName" . }}
  namespace: {{ include "common.namespace" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
  annotations:
    {{- with $.Values.global.envFrom.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.envFrom.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    sealedsecrets.bitnami.com/namespace-wide: "true"
spec:
  template:
    type: Opaque
  encryptedData:
  {{- range $key, $value := .Values.envFrom.useGlobal | ternary $.Values.global.envFrom.sealedSecret .Values.envFrom.sealedSecret -}}
    {{ $key | nindent 4 }}: {{ $value | quote }}
  {{- end -}}
{{- end }}


{{- if and .Values.job.envFrom.sealedSecret (not .Values.job.envFrom.useGlobal) }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ include "common.job.envFrom.sealedSecretName" . }}
  namespace: {{ include "common.namespace" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.job.envFrom.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    sealedsecrets.bitnami.com/namespace-wide: "true"
spec:
  template:
    type: Opaque
  encryptedData:
  {{- range $key, $value := .Values.job.envFrom.sealedSecret -}}
    {{ $key | nindent 4 }}: {{ $value | quote }}
  {{- end -}}
{{- end }}


{{- if and .Values.cronJob.envFrom.sealedSecret (not .Values.cronJob.envFrom.useGlobal) }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ include "common.cronJob.envFrom.sealedSecretName" . }}
  namespace: {{ include "common.namespace" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.cronJob.envFrom.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    sealedsecrets.bitnami.com/namespace-wide: "true"
spec:
  template:
    type: Opaque
  encryptedData:
  {{- range $key, $value := .Values.cronJob.envFrom.sealedSecret -}}
    {{ $key | nindent 4 }}: {{ $value | quote }}
  {{- end -}}
{{- end }}


{{- if and .Values.pod.envFrom.sealedSecret (not .Values.pod.envFrom.useGlobal) }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ include "common.pod.envFrom.sealedSecretName" . }}
  namespace: {{ include "common.namespace" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.pod.envFrom.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    sealedsecrets.bitnami.com/namespace-wide: "true"
spec:
  template:
    type: Opaque
  encryptedData:
  {{- range $key, $value := .Values.pod.envFrom.sealedSecret -}}
    {{ $key | nindent 4 }}: {{ $value | quote }}
  {{- end -}}
{{- end }}


{{- range .Values.sealedSecret }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .name }}
  namespace: {{ include "common.namespace" $ }}
  labels:
    {{- include "common.labels" $ | nindent 4 }}
  annotations:
    {{- with .annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    sealedsecrets.bitnami.com/namespace-wide: "true"
spec:
  template:
    type: {{ default "Opaque" .type }}
  encryptedData:
    {{- .encryptedData | nindent 4 }}
{{- end }}


{{- range .Values.job.sealedSecret }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .name }}
  namespace: {{ include "common.namespace" $ }}
  labels:
    {{- include "common.labels" $ | nindent 4 }}
  annotations:
    {{- with .annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    sealedsecrets.bitnami.com/namespace-wide: "true"
spec:
  template:
    type: {{ default "Opaque" .type }}
  encryptedData:
    {{- .encryptedData | nindent 4 }}
{{- end }}


{{- range .Values.cronJob.sealedSecret }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .name }}
  namespace: {{ include "common.namespace" $ }}
  labels:
    {{- include "common.labels" $ | nindent 4 }}
  annotations:
    {{- with .annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    sealedsecrets.bitnami.com/namespace-wide: "true"
spec:
  template:
    type: {{ default "Opaque" .type }}
  encryptedData:
    {{- .encryptedData | nindent 4 }}
{{- end }}


{{- range .Values.pod.sealedSecret }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .name }}
  namespace: {{ include "common.namespace" $ }}
  labels:
    {{- include "common.labels" $ | nindent 4 }}
  annotations:
    {{- with .annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    sealedsecrets.bitnami.com/namespace-wide: "true"
spec:
  template:
    type: {{ default "Opaque" .type }}
  encryptedData:
    {{- .encryptedData | nindent 4 }}
{{- end }}