{{- if or (and .Values.envFrom.sealedSecret (not .Values.envFrom.useGlobal)) (and $.Values.global.envFrom.sealedSecret .Values.envFrom.createGlobal) }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ include "common.envFrom.sealedSecretName" . }}
  namespace: {{ include "common.namespace" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
spec:
  template:
    type: Opaque
  encryptedData:
  {{- range $key, $value := .Values.envFrom.useGlobal | ternary $.Values.global.envFrom.sealedSecret .Values.envFrom.sealedSecret -}}
    {{ $key | nindent 4 }}: {{ $value | quote }}
  {{- end -}}
{{- end }}


{{- range .Values.sealedSecret }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .name }}
  namespace: {{ include "common.namespace" $ }}
  labels:
    {{- include "common.labels" $ | nindent 4 }}
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
spec:
  template:
    type: {{ default "Opaque" .type }}
  encryptedData:
    {{- .encryptedData | nindent 4 }}
{{- end }}