{{- if or (and .Values.envFrom.secret (not .Values.envFrom.useGlobal)) (and $.Values.global.envFrom.secret .Values.envFrom.createGlobal) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.envFrom.secretName" . }}
  namespace: {{ include "common.namespace" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
type: Opaque
stringData:
{{- range $key, $value := .Values.envFrom.useGlobal | ternary $.Values.global.envFrom.secret .Values.envFrom.secret -}}
  {{ $key | nindent 2 }}: {{ $value | quote }}
{{- end }}
{{- end }}


{{- range .Values.secret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  namespace: {{ include "common.namespace" $ }}
  labels:
    {{- include "common.labels" $ | nindent 4 }}
type: {{ default "Opaque" .type }}
{{- with .data }}
data:
{{- . | nindent 2}}
{{- end }}
{{- with .stringData }}
stringData:
{{- . | nindent 2 }}
{{- end }}
{{- end }}