{{- if or (and .Values.imagePullSecret.url (not .Values.imagePullSecret.useGlobal)) .Values.imagePullSecret.createGlobal }}
{{- $annotations := .Values.imagePullSecret.createGlobal | ternary $.Values.global.imagePullSecret.annotations .Values.imagePullSecret.annotations }}
{{- $url := .Values.imagePullSecret.createGlobal | ternary $.Values.global.imagePullSecret.url .Values.imagePullSecret.url }}
{{- $username := .Values.imagePullSecret.createGlobal | ternary $.Values.global.imagePullSecret.username .Values.imagePullSecret.username }}
{{- $password := .Values.imagePullSecret.createGlobal | ternary $.Values.global.imagePullSecret.password .Values.imagePullSecret.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.containerRegistryName" . }}
  namespace: {{ include "common.namespace" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
  {{- with $annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf "{\"auths\": {\"%s\": {\"auth\": \"%s\"}}}" $url (printf "%s:%s" $username $password | b64enc) | b64enc }}
{{- end }}