{{- if .Values.ingress.enabled }}
{{- range .Values.ingress.tls }}
{{- if .certificate }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ default (include "common.tls.secretName" $) .secretName  }}
  namespace: {{ include "common.namespace" $ }}
  labels:
    {{- include "common.labels" $ | nindent 4 }}
type: kubernetes.io/tls
stringData:
  tls.crt: |
{{ .certificate | indent 4 }}
  tls.key: |
{{ .key | indent 4 }}
{{- end }}
{{- end }}
{{- end }}