{{- if or (and .Values.envFrom.secret (not .Values.envFrom.useGlobal)) (and $.Values.global.envFrom.secret .Values.envFrom.createGlobal) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.envFrom.secretName" . }}
  namespace: {{ include "common.namespace" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
  {{- if or $.Values.global.envFrom.annotations .Values.envFrom.annotations }}
  annotations:
    {{- with $.Values.global.envFrom.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.envFrom.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
type: Opaque
stringData:
{{- range $key, $value := .Values.envFrom.useGlobal | ternary $.Values.global.envFrom.secret .Values.envFrom.secret -}}
  {{ $key | nindent 2 }}: {{ $value | quote }}
{{- end }}
{{- end }}


{{- if and .Values.job.envFrom.secret (not .Values.job.envFrom.useGlobal) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.job.envFrom.secretName" . }}
  namespace: {{ include "common.namespace" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
  {{- with .Values.job.envFrom.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
{{- range $key, $value := .Values.job.envFrom.secret -}}
  {{ $key | nindent 2 }}: {{ $value | quote }}
{{- end }}
{{- end }}


{{- if and .Values.cronJob.envFrom.secret (not .Values.cronJob.envFrom.useGlobal) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.cronJob.envFrom.secretName" . }}
  namespace: {{ include "common.namespace" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
  {{- with .Values.cronJob.envFrom.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
{{- range $key, $value := .Values.cronJob.envFrom.secret -}}
  {{ $key | nindent 2 }}: {{ $value | quote }}
{{- end }}
{{- end }}


{{- if and .Values.pod.envFrom.secret (not .Values.pod.envFrom.useGlobal) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.pod.envFrom.secretName" . }}
  namespace: {{ include "common.namespace" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
  {{- with .Values.pod.envFrom.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
{{- range $key, $value := .Values.pod.envFrom.secret -}}
  {{ $key | nindent 2 }}: {{ $value | quote }}
{{- end }}
{{- end }}


{{- range .Values.secret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  namespace: {{ include "common.namespace" $ }}
  labels:
    {{- include "common.labels" $ | nindent 4 }}
  {{- with .annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: {{ default "Opaque" .type }}
{{- with .data }}
data:
{{- . | nindent 2}}
{{- end }}
{{- with .stringData }}
stringData:
{{- . | nindent 2 }}
{{- end }}
{{- end }}


{{- range .Values.job.secret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  namespace: {{ include "common.namespace" $ }}
  labels:
    {{- include "common.labels" $ | nindent 4 }}
  {{- with .annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: {{ default "Opaque" .type }}
{{- with .data }}
data:
{{- . | nindent 2}}
{{- end }}
{{- with .stringData }}
stringData:
{{- . | nindent 2 }}
{{- end }}
{{- end }}


{{- range .Values.cronJob.secret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  namespace: {{ include "common.namespace" $ }}
  labels:
    {{- include "common.labels" $ | nindent 4 }}
  {{- with .annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: {{ default "Opaque" .type }}
{{- with .data }}
data:
{{- . | nindent 2}}
{{- end }}
{{- with .stringData }}
stringData:
{{- . | nindent 2 }}
{{- end }}
{{- end }}


{{- range .Values.pod.secret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  namespace: {{ include "common.namespace" $ }}
  labels:
    {{- include "common.labels" $ | nindent 4 }}
  {{- with .annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: {{ default "Opaque" .type }}
{{- with .data }}
data:
{{- . | nindent 2}}
{{- end }}
{{- with .stringData }}
stringData:
{{- . | nindent 2 }}
{{- end }}
{{- end }}