{{- if and .Values.ingress.tls.enabled .Values.ingress.tls.certificate }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.tls.secretName" . }}
  namespace: {{ include "common.namespace" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
type: kubernetes.io/tls
stringData:
  tls.crt: |
{{ .Values.ingress.tls.certificate | indent 4 }}
  tls.key: |
{{ .Values.ingress.tls.key | indent 4 }}
{{- end }}