{{- if ne .Values.service.create false }}
{{- with .Values.service }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.serviceName" $ }}
  namespace: {{ include "common.namespace" $ }}
  labels:
    {{- include "common.labels" $ | nindent 4 }}
spec:
  type: {{ default "ClusterIP" .type }}
  selector:
    {{- include "common.selectorLabels" $ | nindent 4 }}
  {{- if .headless }}
  clusterIP: ""
  {{- end }}
  ports:
    - name: {{ .portName }}
      port: {{ .portNumber }}
      targetPort: {{ default .portNumber .containerPort }}
      protocol: {{ default "TCP" .protocol }}
{{- end }}
{{- end }}