{{- if ne .Values.service.create false }}
{{- with .Values.service }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.serviceName" $ }}
  namespace: {{ include "common.namespace" $ }}
  labels:
    {{- include "common.labels" $ | nindent 4 }}
  {{- with .annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .type }}
  {{- if (and (eq .type "ClusterIP") .headless (not .clusterIP)) }}
  clusterIP: ""
  {{- else if .clusterIP }}
  clusterIP: {{ .clusterIP }}
  {{- end }}
  {{- if (and (eq .type "LoadBalancer") .loadBalancerIP) }}
  loadBalancerIP: {{ .loadBalancerIP }}
  {{- end }}
  selector:
    {{- include "common.selectorLabels" $ | nindent 4 }}
  ports:
    - name: {{ .portName }}
      port: {{ .portNumber }}
      targetPort: {{ default .portNumber .containerPort }}
      protocol: {{ default "TCP" .protocol }}
{{- end }}
{{- end }}