apiVersion: v1
kind: Service
metadata:
  name: {{ include "web-app.fullname" . }}
  namespace: {{ include "web-app.namespace" . }}
  labels:
    {{- include "web-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "web-app.selectorLabels" . | nindent 4 }}
  ports:
    {{- with .Values.service  }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .name }}
      protocol: {{ .protocol }}
    {{- end }}
