{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
  name: {{ include "common.serviceAccountName" . }}
  namespace: {{ include "common.namespace" . }}
{{- end }}

{{- if and .Values.job.serviceAccount.create (and (ne (include "common.serviceAccountName" .) (include "common.job.serviceAccountName" .))) }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  {{- with .Values.job.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
  name: {{ include "common.job.serviceAccountName" . }}
  namespace: {{ include "common.namespace" . }}
{{- end }}

{{- if and .Values.cronJob.serviceAccount.create (and (ne (include "common.serviceAccountName" .) (include "common.cronJob.serviceAccountName" .))) }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  {{- with .Values.cronJob.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
  name: {{ include "common.cronJob.serviceAccountName" . }}
  namespace: {{ include "common.namespace" . }}
{{- end }}

{{- if and .Values.pod.serviceAccount.create (and (ne (include "common.serviceAccountName" .) (include "common.pod.serviceAccountName" .))) }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  {{- with .Values.pod.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
  name: {{ include "common.pod.serviceAccountName" . }}
  namespace: {{ include "common.namespace" . }}
{{- end }}
