{{- if .Values.gateway }}
{{- if .Values.gateway.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ .Values.gateway.name | default "envoy-gateway" }}
  namespace: {{ .Values.gateway.namespace | default .Release.Namespace }}
  annotations:
    {{- toYaml .Values.gateway.annotations | nindent 4 }}
spec:
  gatewayClassName: envoy-gateway
  listeners:
    {{- range .Values.gateway.listeners }}
    - name: {{ .name }}
      protocol: {{ .protocol }}
      port: {{ .port }}
      {{- if .hostname }}
      hostname: {{ .hostname | quote }}
      {{- end }}
      {{- if .tls }}
      tls:
        {{- toYaml .tls | nindent 8 }}
      {{- end }}
      allowedRoutes:
        namespaces:
          from: {{ .allowedRoutesFrom | default "All" }}
    {{- end }}
  {{- if .Values.gateway.infrastructure }}
  infrastructure:
    {{- toYaml .Values.gateway.infrastructure | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
