{{- if .Values.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: envoy-gateway
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: envoy-gateway
    app.kubernetes.io/component: control-plane
spec:
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      control-plane: envoy-gateway
  endpoints:
    - port: metrics
      path: /metrics
      interval: {{ .Values.metrics.interval }}
{{- end }}
