{{- if and (not .Values.roleBinding.enabled) .Values.kubeConfig.enabled }}
apiVersion: v1
kind: Config
clusters:
  - name: {{ .Values.kubeConfig.cluster.name }}
    cluster:
      server: {{ .Values.kubeConfig.cluster.server }}
      certificate-authority-data: {{ .Values.kubeConfig.cluster.certificateAuthorityData }}
users:
  - name: {{ .Values.kubeConfig.user.name }}
    user:
      token: {{ .Values.kubeConfig.user.token }}
contexts:
  - name: {{ printf "%s@%s" .Values.kubeConfig.user.name .Values.kubeConfig.cluster.name }}
    context:
      cluster: {{ .Values.kubeConfig.cluster.name }}
      namespace: {{ default "default" .Values.serviceAccount.namespaceOverride }}
      user: {{ .Values.kubeConfig.user.name }}
current-context: {{ printf "%s@%s" .Values.kubeConfig.user.name .Values.kubeConfig.cluster.name }}
preferences: {}
{{- end }}