{{- if and .Values.roleBinding.enabled (ne .Values.serviceAccount.namespaceOverride "default") (not .Values.kubeConfig.enabled) (include "kube-rbac.allUsers" . | fromJsonArray) }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.serviceAccount.namespaceOverride }}
  labels:
    {{- include "kube-rbac.labels" $ | nindent 4 }}
{{- end }}