{{- if and .Values.roleBinding.enabled (not .Values.kubeConfig.enabled) }}
{{- range $username := include "kube-rbac.allUsers" . | fromJsonArray }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kube-rbac.username" $username }}
  namespace: {{ include "kube-rbac.serviceAccount.namespace" $ }}
  labels:
    {{- include "kube-rbac.labels" $ | nindent 4 }}
    {{- include "kube-rbac.userLabels" $username | nindent 4 }}
  {{- with $.Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}