{{- range $.Values.grafana.envFromSecrets }}
{{- if .encryptedData }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .name }}
  namespace: {{ template "grafana.namespace" }}
  labels:
    helm.sh/chart: {{ printf "%s-%s" $.Chart.Name $.Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" }}
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/version: {{ $.Values.grafana.image.tag | default $.Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
  annotations:
    {{- with .annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    sealedsecrets.bitnami.com/namespace-wide: "true"
spec:
  template:
    type: Opaque
  encryptedData:
  {{- range $key, $value := .encryptedData -}}
    {{ $key | nindent 4 }}: {{ $value | quote }}
  {{- end -}}
{{- end }}
{{- end }}