{
 "title": "Redis",
 "description": "Redis Dashboard for Prometheus Redis Exporter 1.x, it works with helm stable/redis-ha exporter.\r\n\r\nIf you missing redis memory utilization, please modify \"maxmemory\" value in values.yaml",
 "tags": [
  "prometheus",
  "redis"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(redis_up,namespace)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(redis_up{namespace=\"$namespace\"},pod)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(redis_up{namespace=\"$namespace\", pod=\"$pod\"},instance)"
    }
   },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(redis_up{namespace=\"$namespace\"},job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(max_over_time(redis_uptime_in_seconds{instance=~\"$instance\",job=\"$job\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Clients",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_connected_clients{instance=~\"$instance\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (redis_memory_used_bytes{instance=~\"$instance\",job=\"$job\"}  / redis_memory_max_bytes{instance=~\"$instance\",job=\"$job\"} )"
    }
   ]
  },
  {
   "title": "Commands Executed / sec",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(redis_commands_processed_total{instance=~\"$instance\",job=\"$job\"}[1m])"
    }
   ]
  },
  {
   "title": "Hits / Misses per Sec",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(redis_keyspace_hits_total{instance=~\"$instance\",job=\"$job\"}[5m])",
     "legendFormat": "hits"
    },
    {
     "expr": "irate(redis_keyspace_misses_total{instance=~\"$instance\",job=\"$job\"}[5m])",
     "legendFormat": "misses"
    }
   ]
  },
  {
   "title": "Total Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "redis_memory_used_bytes{instance=~\"$instance\",job=\"$job\"} ",
     "legendFormat": "used [{{ instance }}]"
    },
    {
     "expr": "redis_memory_max_bytes{instance=~\"$instance\",job=\"$job\"} ",
     "legendFormat": "max [{{ instance }}]"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(redis_net_input_bytes_total{instance=~\"$instance\",job=\"$job\"}[5m])",
     "legendFormat": "input [{{ instance }}]"
    },
    {
     "expr": "rate(redis_net_output_bytes_total{instance=~\"$instance\",job=\"$job\"}[5m])",
     "legendFormat": "output [{{ instance }}]"
    }
   ]
  },
  {
   "title": "Total Items per DB",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum (redis_db_keys{instance=~\"$instance\",job=\"$job\"}) by (db)",
     "legendFormat": "{{ db }} "
    }
   ]
  },
  {
   "title": "Expiring vs Not-Expiring Keys",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (redis_db_keys{instance=~\"$instance\",job=\"$job\"}) - sum (redis_db_keys_expiring{instance=~\"$instance\",job=\"$job\"}) ",
     "legendFormat": "not expiring"
    },
    {
     "expr": "sum (redis_db_keys_expiring{instance=~\"$instance\",job=\"$job\"}) ",
     "legendFormat": "expiring"
    }
   ]
  },
  {
   "title": "Expired / Evicted",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(redis_expired_keys_total{instance=~\"$instance\",job=\"$job\"}[5m])) by (instance)",
     "legendFormat": "expired"
    },
    {
     "expr": "sum(rate(redis_evicted_keys_total{instance=~\"$instance\",job=\"$job\"}[5m])) by (instance)",
     "legendFormat": "evicted"
    }
   ]
  },
  {
   "title": "Command Calls / sec",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(5, irate(redis_commands_total{instance=~\"$instance\",job=\"$job\"} [1m]))",
     "legendFormat": "{{ cmd }}"
    }
   ]
  },
  {
   "title": "Redis connected clients",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "redis_connected_clients{instance=~\"$instance\",job=\"$job\"}",
     "legendFormat": "instance [{{ instance }}]"
    }
   ]
  }
 ]
}