{
 "title": "Redis / Cluster",
 "description": "Prometheus dashboard for Redis servers",
 "tags": [
  "prometheus",
  "redis"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(redis_up,namespace)"
    }
   },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(redis_up{namespace=\"$namespace\"},job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Cluster Uptime",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(max_over_time(redis_uptime_in_seconds{namespace=\"$namespace\", job=\"$job\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "natel-discrete-panel",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "redis_up{namespace=\"$namespace\", job=\"$job\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Master",
   "type": "natel-discrete-panel",
   "description": "Masters have non-zero connected slaves",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "redis_connected_slaves{namespace=\"$namespace\", job=\"$job\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Commands Executed / sec",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(redis_commands_processed_total{namespace=\"$namespace\", job=\"$job\"}[5m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Hits / Misses per Sec",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(redis_keyspace_hits_total{namespace=\"$namespace\", job=\"$job\"}[5m])",
     "legendFormat": "{{pod}}-hits"
    },
    {
     "expr": "irate(redis_keyspace_misses_total{namespace=\"$namespace\", job=\"$job\"}[5m])",
     "legendFormat": "{{pod}}-misses"
    }
   ]
  },
  {
   "title": "Total Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "redis_memory_used_bytes{namespace=\"$namespace\", job=\"$job\"} ",
     "legendFormat": "{{pod}}-used"
    },
    {
     "expr": "redis_config_maxmemory{namespace=\"$namespace\", job=\"$job\"} ",
     "legendFormat": "{{pod}}-max"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(redis_net_input_bytes_total{namespace=\"$namespace\", job=\"$job\"}[5m])",
     "legendFormat": "{{pod}}-input"
    },
    {
     "expr": "rate(redis_net_output_bytes_total{namespace=\"$namespace\", job=\"$job\"}[5m])",
     "legendFormat": "{{pod}}-output"
    }
   ]
  },
  {
   "title": "Command Calls / sec",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(5, irate(redis_commands_total{namespace=\"$namespace\", job=\"$job\"} [1m]))",
     "legendFormat": "{{ cmd }}"
    }
   ]
  },
  {
   "title": "Expiring vs Not-Expiring Keys",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (redis_db_keys{namespace=\"$namespace\", job=\"$job\"}) - sum (redis_db_keys_expiring{namespace=\"$namespace\", job=\"$job\"}) ",
     "legendFormat": "not expiring"
    },
    {
     "expr": "sum (redis_db_keys_expiring{namespace=\"$namespace\", job=\"$job\"}) ",
     "legendFormat": "expiring"
    }
   ]
  },
  {
   "title": "Total Items per DB",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum (redis_db_keys{namespace=\"$namespace\", job=\"$job\"}) by (db)",
     "legendFormat": "{{ db }}"
    }
   ]
  },
  {
   "title": "Expired / Evicted",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(redis_expired_keys_total{namespace=\"$namespace\", job=\"$job\"}[5m])) by (addr)",
     "legendFormat": "expired"
    },
    {
     "expr": "sum(rate(redis_evicted_keys_total{namespace=\"$namespace\", job=\"$job\"}[5m])) by (addr)",
     "legendFormat": "evicted"
    }
   ]
  }
 ]
}