{{- if .Values.backendTLSPolicy.enabled -}}
{{- $fullName := include "gateway-api.fullname" . -}}
{{- $backendTLSPolicy := .Values.backendTLSPolicy -}}
apiVersion: gateway.networking.k8s.io/v1
kind: BackendTLSPolicy
metadata:
  name: {{ $backendTLSPolicy.nameOverride | default (printf "%s-%s" $fullName ($backendTLSPolicy.name | default "")) | trunc 63 | trimSuffix "-" }}
  namespace: {{ include "gateway-api.namespace" . }}
  labels:
    {{- include "gateway-api.labels" . | nindent 4 }}
    {{- with $backendTLSPolicy.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with $backendTLSPolicy.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with $backendTLSPolicy.targetRefs }}
  targetRefs:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $backendTLSPolicy.validation }}
  validation:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
