{{- if .Values.referenceGrant.enabled -}}
apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: {{ include "gateway-api.fullname" . }}
  namespace: {{ include "gateway-api.namespace" . }}
  labels:
    {{- include "gateway-api.labels" . | nindent 4 }}
    {{- with .Values.referenceGrant.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.referenceGrant.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.referenceGrant.from }}
  from:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.referenceGrant.to }}
  to:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
