{{- if .Values.tcpRoute.enabled -}}
{{- $fullName := include "gateway-api.fullname" . -}}
{{- $tcpRoute := .Values.tcpRoute -}}
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
  name: {{ include "gateway-api.resourceName" (mergeOverwrite . $tcpRoute) }}
  namespace: {{ include "gateway-api.namespace" . }}
  labels:
    {{- include "gateway-api.labels" . | nindent 4 }}
    {{- with $tcpRoute.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with $tcpRoute.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  parentRefs:
    {{- with $tcpRoute.parentRefs }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with $tcpRoute.rules }}
  rules:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
