{{- if .Values.tcpRoute.enabled -}}
{{- $fullName := include "gateway-api.fullname" . -}}
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
  name: {{ .Values.tcpRoute.nameOverride | default (printf "%s-%s" $fullName (.Values.tcpRoute.name | default "")) | trunc 63 | trimSuffix "-" }}
  namespace: {{ include "gateway-api.namespace" . }}
  labels:
    {{- include "gateway-api.labels" . | nindent 4 }}
    {{- with .Values.tcpRoute.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.tcpRoute.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  parentRefs:
    {{- with .Values.tcpRoute.parentRefs }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.tcpRoute.rules }}
  rules:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
