{{- if .Values.tlsRoute.enabled -}}
{{- $fullName := include "gateway-api.fullname" . -}}
{{- $tlsRoute := .Values.tlsRoute -}}
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TLSRoute
metadata:
  name: {{ $tlsRoute.nameOverride | default (printf "%s-%s" $fullName ($tlsRoute.name | default "")) | trunc 63 | trimSuffix "-" }}
  namespace: {{ include "gateway-api.namespace" . }}
  labels:
    {{- include "gateway-api.labels" . | nindent 4 }}
    {{- with $tlsRoute.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with $tlsRoute.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  parentRefs:
    {{- with $tlsRoute.parentRefs }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with $tlsRoute.hostnames }}
  hostnames:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $tlsRoute.rules }}
  rules:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
