{{- if .Values.udpRoute.enabled -}}
{{- $fullName := include "gateway-api.fullname" . -}}
{{- $udpRoute := .Values.udpRoute -}}
apiVersion: gateway.networking.k8s.io/v1
kind: UDPRoute
metadata:
  name: {{ include "gateway-api.resourceName" (mergeOverwrite . $udpRoute) }}
  namespace: {{ include "gateway-api.namespace" . }}
  labels:
    {{- include "gateway-api.labels" . | nindent 4 }}
    {{- with $udpRoute.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with $udpRoute.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  parentRefs:
    {{- with $udpRoute.parentRefs }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with $udpRoute.rules }}
  rules:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
