{{- range .Values.repositories }}
{{- if or .auth.sealedPassword .auth.sealedSshPrivateKey }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ include "argocd.repo.secretName" . }}
  namespace: {{ include "common.namespace" $ }}
  labels:
    {{- include "common.labels" $ | nindent 4 }}
    {{- include "argocd.repo.labels" $ | nindent 4 }}
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
spec:
  template:
    type: Opaque
  encryptedData:
    url: {{ .url }}
    {{- if eq (.type | toString) "helm" }}
    type: helm
    {{- end }}
    {{- if or .auth.username .auth.sealedPassword }}
    username: {{ .auth.username }}
    password: {{ .auth.sealedPassword | quote }}
    {{- end }}
    {{- with .auth.sealedSshPrivateKey }}
    sshPrivateKey: {{ . | quote }}
    {{- end }}
{{- else }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "argocd.repo.secretName" . }}
  namespace: {{ include "common.namespace" $ }}
  labels:
    {{- include "common.labels" $ | nindent 4 }}
    {{- include "argocd.repo.labels" $ | nindent 4 }}
stringData:
  url: {{ .url }}
  {{- if eq (.type | toString) "helm" }}
  type: helm
  {{- else }}
  type: git
  {{- end }}
  {{- if or .auth.username .auth.password }}
  username: {{ .auth.username }}
  password: {{ .auth.password }}
  {{- end }}
  {{- with .auth.sshPrivateKey }}
  sshPrivateKey: |
    {{- . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}