{{- range .Values.credentials }}
{{- if or .auth.sealedPassword .auth.sealedSshPrivateKey .auth.sealedGithubAppPrivateKey }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ include "argocd.creds.secretName" . }}
  namespace: {{ include "common.namespace" $ }}
  labels:
    {{- include "common.labels" $ | nindent 4 }}
    {{- include "argocd.creds.labels" $ | nindent 4 }}
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
spec:
  template:
    type: Opaque
  encryptedData:
    url: {{ .url }}
    {{- if or .auth.username .auth.sealedPassword }}
    username: {{ .auth.username }}
    password: {{ .auth.sealedPassword }}
    {{- end }}
    {{- with .auth.sealedSshPrivateKey }}
    sshPrivateKey: {{ . }}
    {{- end }}
    {{- with .auth.githubAppID }}
    githubAppID: {{ . }}
    {{- end }}
    {{- with .auth.githubAppInstallationID }}
    githubAppInstallationID: {{ . }}
    {{- end }}
    {{- with .auth.githubAppEnterpriseBaseUrl }}
    githubAppEnterpriseBaseUrl: {{ . }}
    {{- end }}
    {{- with .auth.sealedGithubAppPrivateKey }}
    githubAppPrivateKey: {{ . }}
    {{- end }}
{{- else }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "argocd.creds.secretName" . }}
  namespace: {{ include "common.namespace" $ }}
  labels:
    {{- include "common.labels" $ | nindent 4 }}
    {{- include "argocd.creds.labels" $ | nindent 4 }}
stringData:
  url: {{ .url }}
  {{- if or .auth.username .auth.password }}
  username: {{ .auth.username }}
  password: {{ .auth.password }}
  {{- end }}
  {{- with .auth.sshPrivateKey }}
  sshPrivateKey: |
    {{- . | nindent 4}}
  {{- end }}
  {{- with .auth.githubAppID }}
  githubAppID: {{ . }}
  {{- end }}
  {{- with .auth.githubAppInstallationID }}
  githubAppInstallationID: {{ . }}
  {{- end }}
  {{- with .auth.githubAppEnterpriseBaseUrl }}
  githubAppEnterpriseBaseUrl: {{ . }}
  {{- end }}
  {{- with .auth.githubAppPrivateKey }}
  githubAppPrivateKey: |
    {{- . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}