{
 "title": "JMX Exporter / httpserver",
 "description": "jmx-exporter monitor",
 "tags": [
  "jmx",
  "httpserver",
  "prometheus",
  "kubernetes",
  "prometheus-operator"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(up{job=\"jmx-exporter\"}, namespace)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(up{job=\"jmx-exporter\",namespace=\"$namespace\"}, pod)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(up{job=\"jmx-exporter\", pod=\"$pod\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "java_lang_OperatingSystem",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "description": "up",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"jmx-exporter\", pod=\"$pod\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "java_lang_Runtime_Uptime",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "java_lang_runtime_uptime{job=\"jmx-exporter\", pod=\"$pod\", instance=\"$instance\"} / 1000"
    }
   ]
  },
  {
   "title": "Start time",
   "type": "stat",
   "description": "java_lang_Runtime_StartTime",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "java_lang_runtime_starttime{job=\"jmx-exporter\", pod=\"$pod\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Open file descriptors",
   "type": "stat",
   "description": "java_lang_OperatingSystem_OpenFileDescriptorCount",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "java_lang_operatingsystem_openfiledescriptorcount{job=\"jmx-exporter\", pod=\"$pod\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "CPU System Load(1m avg)",
   "type": "gauge",
   "description": "java_lang_OperatingSystem_SystemCpuLoad",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(java_lang_operatingsystem_systemcpuload{job=\"jmx-exporter\", pod=\"$pod\", instance=\"$instance\"}[1m]) * 100"
    }
   ]
  },
  {
   "title": "CPU Process Load(1m avg)",
   "type": "gauge",
   "description": "java_lang_OperatingSystem_ProcessCpuLoad",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(java_lang_operatingsystem_processcpuload{job=\"jmx-exporter\", pod=\"$pod\", instance=\"$instance\"}[1m]) * 100"
    }
   ]
  },
  {
   "title": "System load average",
   "type": "stat",
   "description": "java_lang_OperatingSystem_SystemLoadAverage",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "java_lang_operatingsystem_systemloadaverage{job=\"jmx-exporter\", pod=\"$pod\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "description": "java_lang_OperatingSystem_AvailableProcessors",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "java_lang_operatingsystem_availableprocessors{job=\"jmx-exporter\", pod=\"$pod\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "java_lang_GarbageCollector",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "GC count",
     "type": "graph",
     "description": "java_lang_GarbageCollector_CollectionCount",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(java_lang_garbagecollector_collectioncount{job=\"jmx-exporter\", pod=\"$pod\", instance=\"$instance\"}[1m])",
       "legendFormat": "name: {{name}}"
      }
     ]
    },
    {
     "title": "GC time / 1 min. rate",
     "type": "graph",
     "description": "java_lang_GarbageCollector_CollectionTime",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(java_lang_garbagecollector_collectiontime{job=\"jmx-exporter\", pod=\"$pod\", instance=\"$instance\"}[1m])",
       "legendFormat": "name: {{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "java_lang_MemoryPool",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Memory Pool Used",
     "type": "graph",
     "description": "java_lang_MemoryPool_Usage_used",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "java_lang_memorypool_usage_used{job=\"jmx-exporter\", pod=\"$pod\", instance=\"$instance\"}",
       "legendFormat": "name: {{name}}"
      }
     ]
    },
    {
     "title": "Memory Pool Committed",
     "type": "graph",
     "description": "java_lang_MemoryPool_Usage_committed",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "java_lang_memorypool_usage_committed{job=\"jmx-exporter\", pod=\"$pod\", instance=\"$instance\"}",
       "legendFormat": "name: {{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "java_lang_Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Memory Heap /NonHeap Used",
   "type": "graph",
   "description": "java_lang_Memory_HeapMemoryUsage_used /  java_lang_Memory_NonHeapMemoryUsage_used",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "java_lang_memory_heapmemoryusage_used{job=\"jmx-exporter\", pod=\"$pod\", instance=\"$instance\"}",
     "legendFormat": "HeapMemory"
    },
    {
     "expr": "java_lang_memory_nonheapmemoryusage_used{job=\"jmx-exporter\", pod=\"$pod\", instance=\"$instance\"}",
     "legendFormat": "NonHeapMemory"
    }
   ]
  },
  {
   "title": "Memory Heap /NonHeap Committed",
   "type": "graph",
   "description": "java_lang_Memory_HeapMemoryUsage_committed /  java_lang_Memory_NonHeapMemoryUsage_committed",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "java_lang_memory_heapmemoryusage_committed{job=\"jmx-exporter\", pod=\"$pod\", instance=\"$instance\"}",
     "legendFormat": "HeapMemory"
    },
    {
     "expr": "java_lang_memory_nonheapmemoryusage_committed{job=\"jmx-exporter\", pod=\"$pod\", instance=\"$instance\"}",
     "legendFormat": "NonHeapMemory"
    }
   ]
  },
  {
   "title": "java_lang_Threading",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Threads Used",
   "type": "graph",
   "description": "java_lang_Threading_ThreadCount",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "java_lang_threading_threadcount{job=\"jmx-exporter\", pod=\"$pod\", instance=\"$instance\"}",
     "legendFormat": "current"
    },
    {
     "expr": "java_lang_threading_daemonthreadcount{job=\"jmx-exporter\", pod=\"$pod\", instance=\"$instance\"}",
     "legendFormat": "daemon"
    }
   ]
  },
  {
   "title": "java_lang_ClassLoading",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Class Loaded / Unloaded",
   "type": "graph",
   "description": "java_lang_ClassLoading_LoadedClassCount / java_lang_ClassLoading_UnloadedClassCount",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "java_lang_classloading_loadedclasscount{job=\"jmx-exporter\", pod=\"$pod\", instance=\"$instance\"}",
     "legendFormat": "loaded"
    },
    {
     "expr": "java_lang_classloading_unloadedclasscount{job=\"jmx-exporter\", pod=\"$pod\", instance=\"$instance\"}",
     "legendFormat": "unloaded"
    }
   ]
  },
  {
   "title": "Catalina",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Catalina Request Processor bytes",
   "type": "graph",
   "description": "Catalina_GlobalRequestProcessor_bytesReceived /  Catalina_GlobalRequestProcessor_bytesSent",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "increase(catalina_globalrequestprocessor_bytesreceived{job=\"jmx-exporter\", pod=\"$pod\", instance=\"$instance\"}[1m])",
     "legendFormat": "{{name}} recv"
    },
    {
     "expr": "increase(catalina_globalrequestprocessor_bytessent{job=\"jmx-exporter\", pod=\"$pod\", instance=\"$instance\"}[1m])",
     "legendFormat": "{{name}} sent"
    }
   ]
  },
  {
   "title": "Catalina Request Processor requests",
   "type": "graph",
   "description": "Catalina_GlobalRequestProcessor_requestCount  /   Catalina_GlobalRequestProcessor_errorCount",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(catalina_globalrequestprocessor_requestcount{job=\"jmx-exporter\", pod=\"$pod\", instance=\"$instance\"}[1m])",
     "legendFormat": "{{name}} count"
    },
    {
     "expr": "increase(catalina_globalrequestprocessor_errorcount{job=\"jmx-exporter\", pod=\"$pod\", instance=\"$instance\"}[1m])",
     "legendFormat": "{{name}} error"
    }
   ]
  },
  {
   "title": "Catalina Request Processing Time",
   "type": "graph",
   "description": "Catalina_GlobalRequestProcessor_processingTime",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 37 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "increase(catalina_globalrequestprocessor_processingtime{job=\"jmx-exporter\", pod=\"$pod\", instance=\"$instance\"}[1m]) / increase(catalina_globalrequestprocessor_requestcount{job=\"jmx-exporter\", pod=\"$pod\", instance=\"$instance\"}[1m])",
     "legendFormat": "name: {{name}}"
    }
   ]
  },
  {
   "title": "Catalina ThreadPool",
   "type": "graph",
   "description": "Catalina_readPool_connectionCount /  Catalina_ThreadPool_currentThreadsBusy  /  Catalina_ThreadPool_connectionCount   /   Catalina_ThreadPool_keepAliveCount",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "catalina_threadpool_currentthreadcount{job=\"jmx-exporter\", instance=\"$instance\"}",
     "legendFormat": "current: {{name}}"
    },
    {
     "expr": "catalina_threadpool_currentthreadsbusy{job=\"jmx-exporter\", instance=\"$instance\"}",
     "legendFormat": "current busy: {{name}}"
    },
    {
     "expr": "catalina_threadpool_connectioncount{job=\"jmx-exporter\", pod=\"$pod\", instance=\"$instance\"}",
     "legendFormat": "connection: {{name}}"
    },
    {
     "expr": "catalina_threadpool_keepalivecount{job=\"jmx-exporter\", pod=\"$pod\", instance=\"$instance\"}",
     "legendFormat": "keepAlive: {{name}}"
    }
   ]
  },
  {
   "title": "Max Threads",
   "type": "graph",
   "description": "Catalina_ThreadPool_maxThreads",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "catalina_threadpool_maxthreads{job=\"jmx-exporter\", pod=\"$pod\", instance=\"$instance\"}",
     "legendFormat": "name: {{name}}"
    }
   ]
  },
  {
   "title": "Min Spare Threads",
   "type": "graph",
   "description": "Catalina_ThreadPool_minSpareThreads",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "catalina_threadpool_minsparethreads{job=\"jmx-exporter\", pod=\"$pod\", instance=\"$instance\"}",
     "legendFormat": "name: {{name}}"
    }
   ]
  },
  {
   "title": "Accept Count",
   "type": "graph",
   "description": "Catalina_ThreadPool_acceptCount",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "catalina_threadpool_acceptcount{job=\"jmx-exporter\", pod=\"$pod\", instance=\"$instance\"}",
     "legendFormat": "name: {{name}}"
    }
   ]
  },
  {
   "title": "Poller Thread Count",
   "type": "graph",
   "description": "Catalina_ThreadPool_pollerThreadCount",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "catalina_threadpool_pollerthreadcount{job=\"jmx-exporter\", pod=\"$pod\", instance=\"$instance\"}",
     "legendFormat": "name: {{name}}"
    }
   ]
  },
  {
   "title": "Top 5 servlet request count",
   "type": "graph",
   "description": "Catalina_Servlet_requestCount",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(5, increase(catalina_servlet_requestcount{job=\"jmx-exporter\", pod=\"$pod\", instance=\"$instance\"}[1m]))",
     "legendFormat": "WebModule: {{WebModule}} Name: {{name}}"
    }
   ]
  },
  {
   "title": "Top 5 servlet error count",
   "type": "graph",
   "description": "Catalina_Servlet_errorCount",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(5, increase(catalina_servlet_errorcount{job=\"jmx-exporter\", pod=\"$pod\", instance=\"$instance\"}[1m]))",
     "legendFormat": "WebModule: {{WebModule}} Name: {{name}}"
    }
   ]
  },
  {
   "title": "Top 5 servlets average processing time per request",
   "type": "graph",
   "description": "Catalina_Servlet_processingTime  /  Catalina_Servlet_requestCount",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "topk(5, increase(catalina_servlet_processingtime{job=\"jmx-exporter\", pod=\"$pod\", instance=\"$instance\"}[1m]) / increase(catalina_servlet_requestcount{job=\"jmx-exporter\", pod=\"$pod\", instance=\"$instance\"}[1m]))",
     "legendFormat": "WebModule: {{WebModule}} Name: {{name}}"
    }
   ]
  },
  {
   "title": "Catalina Manager Sessions",
   "type": "graph",
   "description": "Catalina_Manager_expiredSessions  /   Catalina_Manager_rejectedSessions",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(catalina_manager_expiredsessions{job=\"jmx-exporter\", pod=\"$pod\", instance=\"$instance\"}[1m])) by (instance)",
     "legendFormat": "expired"
    },
    {
     "expr": "sum(increase(catalina_manager_rejectedsessions{job=\"jmx-exporter\", pod=\"$pod\", instance=\"$instance\"}[1m])) by (instance)",
     "legendFormat": "rejected"
    }
   ]
  }
 ]
}