{{- if (index .Values "postgresql-ha" "postgresql" "existingSecretPasswordValue") }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ index .Values "postgresql-ha" "postgresql" "existingSecret" }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  annotations:
    {{- if .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
    sealedsecrets.bitnami.com/namespace-wide: "true"
spec:
  template:
    type: Opaque
  encryptedData:
    {{- if and (index .Values "postgresql-ha" "postgresql" "existingSecretPostgresPasswordValue") (not (eq (index .Values "postgresql-ha" "postgresql" "username") "postgres")) }}
    postgresql-postgres-password: {{ index .Values "postgresql-ha" "postgresql" "existingSecretPostgresPasswordValue" | quote }}
    {{- end }}
    postgresql-password: {{ (index .Values "postgresql-ha" "postgresql" "existingSecretPasswordValue") | quote }}
    repmgr-password: {{ (index .Values "postgresql-ha" "postgresql" "existingSecretRepmgrPasswordValue") | quote }}
{{- end }}


{{- if (index .Values "postgresql-ha" "pgpool" "existingSecretAdminPasswordValue") }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ index .Values "postgresql-ha" "pgpool" "existingSecret" }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: pgpool
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  annotations:
    {{- if .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
    sealedsecrets.bitnami.com/namespace-wide: "true"
spec:
  template:
    type: Opaque
  encryptedData:
    admin-password: {{ (index .Values "postgresql-ha" "pgpool" "existingSecretAdminPasswordValue") | quote }}
{{- end }}


{{- if (index .Values "postgresql-ha" "pgpool" "customUsersSecretPasswordsValue") }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ index .Values "postgresql-ha" "pgpool" "customUsersSecret" }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: pgpool
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  annotations:
    {{- if .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
    sealedsecrets.bitnami.com/namespace-wide: "true"
spec:
  template:
    type: Opaque
  encryptedData:
    usernames: {{ (index .Values "postgresql-ha" "pgpool" "customUsersSecretUsernamesValue") | quote }}
    passwords: {{ (index .Values "postgresql-ha" "pgpool" "customUsersSecretPasswordsValue") | quote }}
{{- end }}
