name: Push Helm chart

on:
  push:
    branches: [ main ]
    paths:
      - 'charts/**'
  # pull_request:
  #   branches: [ main ]
  workflow_dispatch:

env:
  HELM_REPO_URL: https://charts.c3rny.ninja
  PUBLISH_REPO_TARGET_BRANCH: gh-pages
  PUBLISH_PACKAGES_ROOT_PATH: packages
  SOURCE_REPO_URL: ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}
  SOURCE_REPO_DEFAULT_BRANCH: main
  SOURCE_REPO_CLONE_PATH: ${RUNNER_TEMP}/${GITHUB_REPOSITORY}
  SOURCE_REPO_ROOT_PATH: charts
  RUN_CUSTOM: 'false'

jobs:
  push_helm_chart:
    runs-on: ubuntu-latest
    
    outputs: {}
    
    name: Push Helm chart
    steps:
      - name: Checkout GitHub Pages
        uses: actions/checkout@v2
        with:
          ref: ${{ env.PUBLISH_REPO_TARGET_BRANCH }}
          fetch-depth: 0
          persist-credentials: false


      - name: Checkout source repository
        run: |
          mkdir -p ${{ env.SOURCE_REPO_CLONE_PATH }}
          
          git clone ${{ env.SOURCE_REPO_URL }} ${{ env.SOURCE_REPO_CLONE_PATH }}

          echo
          cd ${{ env.SOURCE_REPO_CLONE_PATH }}
          pwd; echo

          echo ":: git log"
          git log -n 1 -- ${{ env.SOURCE_REPO_ROOT_PATH }}

          echo
          git diff-tree --no-commit-id --stat -r ${GITHUB_SHA} -- ${{ env.SOURCE_REPO_ROOT_PATH }}

          echo
          find ${{ env.SOURCE_REPO_ROOT_PATH }} -name "Chart.yaml" 2> /dev/null | uniq

          echo COMMIT_MESSAGE="$(git log --pretty=format:"%B" -n 1 -- ${{ env.SOURCE_REPO_ROOT_PATH }} | grep -E '\(#[0-9]+\)$')" >> $GITHUB_ENV


      - name: Set up Helm
        if: env.COMMIT_MESSAGE != ''
        uses: azure/setup-helm@v1
      
      
      - name: Set up YQ
        if: env.COMMIT_MESSAGE != ''
        uses: chrisdickinson/setup-yq@latest
        with:
          yq-version: v4.16.2
      

      - name: Set up ENV
        if: env.COMMIT_MESSAGE != ''
        run: |
          echo HELM_REPO_NAME=$(basename ${{ env.HELM_REPO_URL }} | sed -r 's|charts\.||') >> $GITHUB_ENV


      - name: Set up Helm repository
        if: env.COMMIT_MESSAGE != ''
        run: |
          helm repo add ${{ env.HELM_REPO_NAME }} ${{ env.HELM_REPO_URL }}
          echo
          helm repo update
      

      - name: Publish packages
        if: env.COMMIT_MESSAGE != ''
        run: |
          cd ${{ env.SOURCE_REPO_CLONE_PATH }}; pwd
          echo

          for CHART_FILE in $(find $(git diff-tree --no-commit-id --name-only -r ${GITHUB_SHA} -- ${{ env.SOURCE_REPO_ROOT_PATH }}) -name "Chart.yaml" 2> /dev/null | uniq); do
              if [ -d "$(dirname ${CHART_FILE})" ]; then
                
                  if [ "${GITHUB_REF_NAME}" != "${{ env.SOURCE_REPO_DEFAULT_BRANCH }}" ]; then
                      yq eval -i '.version = .version + "-alpha"' ${CHART_FILE}
                  fi

                  CHART_NAME="$(yq eval '.name' ${CHART_FILE})"
                  CHART_VERSION="$(yq eval '.version' ${CHART_FILE})"

                  # yq '.dependencies.[] | select(.repository == "https://charts.bitnami.com/bitnami" and .name != "common") | .version' Chart.yaml | head -n 1
                  HELM_REPO_CHART_VERSION="$(helm search repo -r "${HELM_REPO_NAME}/${CHART_NAME}[^-]" --devel --version "${CHART_VERSION}" -o json 2> /dev/null | jq -r '.[].version')"

                  echo
                  echo "****************************************"
                  echo ":: Chart ( ${CHART_NAME} )"
                  
                  helm lint $(dirname ${CHART_FILE})

                  if [ $? -eq 0 ] && [[ -z "${HELM_REPO_CHART_VERSION}" || ! -z "$(grep -oE '\-alpha$' <<< ${HELM_REPO_CHART_VERSION})" ]]; then
                      PUBLISH_PACKAGE_DIRECTORY=""
                      
                      # Package directory
                      PUBLISH_PACKAGE_DIRECTORY="$(cut --delimiter='/' --fields=2  <<< ${CHART_FILE})"
                      PUBLISH_PACKAGE_DIR_PATH=${GITHUB_WORKSPACE}/${{ env.PUBLISH_PACKAGES_ROOT_PATH }}/${PUBLISH_PACKAGE_DIRECTORY}
                      
                      echo; echo "==> Publishing ${PUBLISH_PACKAGE_DIR_PATH}"
                      mkdir -p ${PUBLISH_PACKAGE_DIR_PATH}
                      mv -fv $(helm package $(dirname ${CHART_FILE}) | awk '{ n=split($0, a, /[\/]/); print a[n] }') ${PUBLISH_PACKAGE_DIR_PATH}

                      helm repo index ${PUBLISH_PACKAGE_DIR_PATH} --url ${{ env.HELM_REPO_URL }}/${{ env.PUBLISH_PACKAGES_ROOT_PATH }}/${PUBLISH_PACKAGE_DIRECTORY} --merge ${GITHUB_WORKSPACE}/index.yaml
                      mv -fv ${PUBLISH_PACKAGE_DIR_PATH}/index.yaml ${GITHUB_WORKSPACE}/index.yaml
                  else
                      echo; echo "==> Skipping publish, version ${HELM_REPO_CHART_VERSION} is already published..."
                  fi

                  echo "****************************************"
              fi
          done

          if [ -z "${HELM_REPO_CHART_VERSION}" ] || [ ! -z "$(grep -oE '\-alpha$' <<< ${HELM_REPO_CHART_VERSION})" ]; then
              echo; echo ":: git config"
              cd ${GITHUB_WORKSPACE}
              pwd; echo

              git remote set-url origin "https://x-access-token:${{ secrets.PAT_PUBLIC_MGR }}@github.com/${GITHUB_REPOSITORY}"
              
              git config --local user.email "${GITHUB_ACTOR}@users.noreply.github.com"
              git config --local user.name "${GITHUB_ACTOR}"
              
              echo ":: git add & commit"
              git add .
              git commit -am "${{ env.COMMIT_MESSAGE }}" --allow-empty

              echo; echo ":: git push"
              git push origin ${{ env.PUBLISH_REPO_TARGET_BRANCH }}
          fi