name: Push helm charts

on:
  push:
    branches: [ master ]
    paths:
      - 'charts/**'
  pull_request:
    branches: [ master ]
  workflow_dispatch:
  

env:
  PUBLISH_TARGET_BRANCH: gh-pages
  PUBLISH_PACKAGES_ROOT_PATH: packages
  HELM_CHARTS_REPO_URL: https://charts.c3rny.ninja
  HELM_CHARTS_ROOT_PATH: charts

jobs:
  check_version:
    runs-on: ubuntu-latest
    
    outputs: {}
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Checkout GitHub Pages
        uses: actions/checkout@v2
        with:
          ref: ${{ env.PUBLISH_TARGET_BRANCH }}
          path: "../${{ github.repository }}_${{ env.PUBLISH_TARGET_BRANCH }}"

      - name: Set up Helm
        uses: azure/setup-helm@v1

      - name: Set up YQ
        uses: chrisdickinson/setup-yq@latest

      - name: Set up ENV
        run: |
          echo HELM_CHARTS_REPO_NAME=$(basename ${{ env.HELM_CHARTS_REPO_URL }} | sed -r 's|charts\.||') >> $GITHUB_ENV
        # echo PUBLISH_REPO_NAME=$(basename $(git rev-parse --show-toplevel)) >> $GITHUB_ENV
      
      - run: |
          echo "pwd"
          pwd
          echo
          echo "HELM_CHARTS_REPO_NAME: ${{ env.HELM_CHARTS_REPO_NAME }}"
          echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
          echo "github.repository: ${{ github.repository }}"
          echo
          echo "ls -alh ${GITHUB_WORKSPACE}/../${{ github.repository }}_${{ env.PUBLISH_TARGET_BRANCH }}"
          ls -alh "${GITHUB_WORKSPACE}/../${{ github.repository }}_${{ env.PUBLISH_TARGET_BRANCH }}"
          echo
          helm repo add ${{ env.HELM_CHARTS_REPO_NAME }} ${{ env.HELM_CHARTS_REPO_URL }}
          echo
          helm repo update
          echo
          helm repo list
          echo
          helm search repo -r ${{ env.HELM_CHARTS_REPO_NAME }} -o json --devel
          echo 
          git log --name-only --pretty=format: -n 1 ${{ env.HELM_CHARTS_ROOT_PATH }} | find -name "Chart.yaml" | xargs dirname
