name: Sync Helm chart
  
on:
  # push:
  #   branches: [ main ]
  # pull_request:
  #   branches: [ main ]
  schedule:
    # - cron:  "30 */12 * * *"
    - cron:  "0 6 * * *"
  workflow_dispatch:

  
env:
  PR_BASE_BRANCH: main
  SYNC_SETTINGS_RELATIVE_PATH: .github/workflows/sync.settings.json

jobs:
  set_matrix:
    runs-on: ubuntu-latest

    outputs:
      SYNC_SETTINGS: ${{ steps.setMatrix.outputs.SYNC_SETTINGS }}
    
    steps:
      - uses: actions/checkout@v2

      - id: setMatrix
        run: echo ::set-output name=SYNC_SETTINGS::$(cat ${GITHUB_WORKSPACE}/${{ env.SYNC_SETTINGS_RELATIVE_PATH }})


  sync_chart:
    needs: [ set_matrix ]
    
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.set_matrix.outputs.SYNC_SETTINGS) }}
    
    if: matrix.chart.enabled == 'true'
    
    env:
      CHART_NAME: ${{ matrix.chart.name }}
      CHART_SYNC_TYPE: ${{ matrix.chart.type }}
      REMOTE_CHART_REPO_URL: ${{ matrix.chart.remote.url }}
      REMOTE_CHART_REPO_BRANCH: ${{ matrix.chart.remote.branch }}
      REMOTE_CHART_COMMIT_SHA1: ${{ matrix.chart.remote.commitSHA1 }}
      REMOTE_CHART_ROOT_PATH: ${{ matrix.chart.remote.rootPath }}
      LOCAL_CHART_BASE_PATH: ${{ matrix.chart.local.basePath }}
      LOCAL_CHART_PATH_PREFIX: ${{ matrix.chart.local.pathPrefix }}
      LOCAL_CHART_ROOT_PATH: ${LOCAL_CHART_BASE_PATH}/${LOCAL_CHART_PATH_PREFIX}/${CHART_NAME}
    
    outputs: {}

    name: Sync chart
    steps:

      # checkout
      - uses: actions/checkout@v2
        with:
          fetch-depth: 50


      # Set ENV
      - name: Set ENV
        id: setEnv
        run: |
          REMOTE_CHART_REPO_ORG=$(awk '{ n=split($0, a, /[\/]/); print a[4] }' <<<  ${{ env.REMOTE_CHART_REPO_URL }})

          if [ -z "${{ env.REMOTE_CHART_REPO_NAME }}" ]; then
              REMOTE_CHART_REPO_NAME=$(awk '{ n=split($0, t, /[\/]/); split(t[n], a, /\./); print a[1] }' <<< ${{ env.REMOTE_CHART_REPO_URL }})

              echo REMOTE_CHART_REPO_NAME=${REMOTE_CHART_REPO_NAME} >> $GITHUB_ENV
          else
              REMOTE_CHART_REPO_NAME=${{ env.REMOTE_CHART_REPO_NAME }}
          fi

          if [ -z "${{ env.REMOTE_CHART_FILE_URL }}" ]; then
              if [ ! -z "${{ env.REMOTE_CHART_COMMIT_SHA1 }}" ]; then
                  REMOTE_CHART_FILE_URL="https://raw.githubusercontent.com/${REMOTE_CHART_REPO_ORG}/${REMOTE_CHART_REPO_NAME}/${{ env.REMOTE_CHART_COMMIT_SHA1 }}/$(sed -r 's|/$||' <<< ${{ env.REMOTE_CHART_ROOT_PATH }})/Chart.yaml"
              else
                  REMOTE_CHART_FILE_URL="https://raw.githubusercontent.com/${REMOTE_CHART_REPO_ORG}/${REMOTE_CHART_REPO_NAME}/${{ env.REMOTE_CHART_REPO_BRANCH }}/$(sed -r 's|/$||' <<< ${{ env.REMOTE_CHART_ROOT_PATH }})/Chart.yaml"
              fi

              echo REMOTE_CHART_FILE_URL=${REMOTE_CHART_FILE_URL} >> $GITHUB_ENV
          else
              REMOTE_CHART_FILE_URL=${{ env.REMOTE_CHART_FILE_URL }}
          fi

          echo REMOTE_CHART_NAME=$(awk -F '/' '{ print $NF }' <<< ${{ env.REMOTE_CHART_ROOT_PATH }}) >> $GITHUB_ENV
          echo REMOTE_CHART_REPO_ORG=${REMOTE_CHART_REPO_ORG} >> $GITHUB_ENV


      # Get version
      - name: Get version
        id: getChartVersion
        run: |
          if [ "${{ env.CHART_SYNC_TYPE }}" == "dependency" ]; then
              echo LOCAL_CHART_VERSION=$(yq eval '.dependencies.[] | select(.name == "${{ env.REMOTE_CHART_NAME }}") | .version' ${{ env.LOCAL_CHART_ROOT_PATH }}/Chart.yaml) >> $GITHUB_ENV
          else
              echo LOCAL_CHART_VERSION=$(yq eval '.version' ${{ env.LOCAL_CHART_ROOT_PATH }}/Chart.yaml) >> $GITHUB_ENV
          fi

          echo REMOTE_CHART_VERSION=$(yq eval '.version' <(curl -sSL ${{ env.REMOTE_CHART_FILE_URL }})) >> $GITHUB_ENV
          echo REMOTE_CHART_DESCRIPTION=$(yq eval '.description' <(curl -sSL ${{ env.REMOTE_CHART_FILE_URL }})) >> $GITHUB_ENV
          echo REMOTE_CHART_APPVERSION=$(yq eval '.appVersion' <(curl -sSL ${{ env.REMOTE_CHART_FILE_URL }})) >> $GITHUB_ENV

      
      # Set up Helm
      - name: Set up Helm
        if: env.REMOTE_CHART_VERSION != env.LOCAL_CHART_VERSION
        uses: azure/setup-helm@v1


      # Set up YQ
      - name: Set up YQ
        if: env.REMOTE_CHART_VERSION != env.LOCAL_CHART_VERSION
        uses: chrisdickinson/setup-yq@latest
        with:
          yq-version: v4.16.2
      

      # Clone remote repository
      - name: Clone remote repository
        if: env.REMOTE_CHART_VERSION != env.LOCAL_CHART_VERSION
        run: |
          git clone ${{ env.REMOTE_CHART_REPO_URL }} ${RUNNER_TEMP}/${{ env.REMOTE_CHART_REPO_NAME }}
          
          cd ${RUNNER_TEMP}/${{ env.REMOTE_CHART_REPO_NAME }}
          
          if [ ! -z "${{ env.REMOTE_CHART_COMMIT_SHA1 }}" ]; then
              git reset --hard ${{ env.REMOTE_CHART_COMMIT_SHA1 }}
          fi

          echo
          git log --stat --pretty=format: -n 1 -- ${{ env.REMOTE_CHART_ROOT_PATH }}

          echo
          echo ORIGINAL_COMMIT_ID=$(git log --pretty=format:"%H" -n 1 -- ${{ env.REMOTE_CHART_ROOT_PATH }}) >> $GITHUB_ENV
          echo ORIGINAL_COMMIT_AUTHOR_NAME=$(git log --pretty=format:"%aN" -n 1 -- ${{ env.REMOTE_CHART_ROOT_PATH }}) >> $GITHUB_ENV
          echo ORIGINAL_COMMIT_AUTHOR_EMAIL=$(git log --pretty=format:"%aE" -n 1 -- ${{ env.REMOTE_CHART_ROOT_PATH }}) >> $GITHUB_ENV
          echo ORIGINAL_COMMIT_DATE=$(git log --pretty=format:"%aD" -n 1 -- ${{ env.REMOTE_CHART_ROOT_PATH }}) >> $GITHUB_ENV
          echo ORIGINAL_COMMIT_MESSAGE=$(git log --pretty=format:"%B" -n 1 -- ${{ env.REMOTE_CHART_ROOT_PATH }}) >> $GITHUB_ENV
          echo ORIGINAL_COMMIT_URL=$(sed -r "s/\.git$/\/commit\/$(git log --pretty=format:"%H" -n 1 -- ${{ env.REMOTE_CHART_ROOT_PATH }})/" <<< ${{ env.REMOTE_CHART_REPO_URL }}) >> $GITHUB_ENV


      # Import new or update existing chart
      - name: Import new or update existing chart
        if: env.REMOTE_CHART_VERSION != env.LOCAL_CHART_VERSION && env.CHART_SYNC_TYPE == 'src'
        run: |
          if [ ! -d "${GITHUB_WORKSPACE}/${{ env.LOCAL_CHART_ROOT_PATH }}" ]; then
              mkdir -p ${GITHUB_WORKSPACE}/${{ env.LOCAL_CHART_ROOT_PATH }}
              cp -rfv ${RUNNER_TEMP}/${{ env.REMOTE_CHART_REPO_NAME }}/${{ env.REMOTE_CHART_ROOT_PATH }}/* ${GITHUB_WORKSPACE}/${{ env.LOCAL_CHART_ROOT_PATH }}/

          else
              pwd; echo

              LOCAL_CHART_REMOTE_COMMIT_ID=$(git log --pretty=format:"%B" -n 1 -- ${{ env.LOCAL_CHART_ROOT_PATH }} | awk -F '[][]' '{print $2}')
              
              cd ${RUNNER_TEMP}/${{ env.REMOTE_CHART_REPO_NAME }}
              pwd; echo

              if [ ! -z "${{ env.REMOTE_CHART_COMMIT_SHA1 }}" ]; then
                  git reset --hard ${{ env.REMOTE_CHART_COMMIT_SHA1 }}
              else
                  git reset --hard ${{ env.ORIGINAL_COMMIT_ID }}
              fi

              if [ ! -z "${LOCAL_CHART_REMOTE_COMMIT_ID}" ]; then
                  echo

                  # Create patch
                  PATCH_VERSION=$(yq eval '.version' ${{ env.REMOTE_CHART_ROOT_PATH }}/Chart.yaml)
                  PATCH_FILE_PATH=${RUNNER_TEMP}/${{ env.CHART_NAME }}_patch-${PATCH_VERSION}.diff

                  echo "git diff --no-prefix --output ${PATCH_FILE_PATH} ${LOCAL_CHART_REMOTE_COMMIT_ID} HEAD^ -- ${{ env.REMOTE_CHART_ROOT_PATH }}"
                  git diff --no-prefix --output ${PATCH_FILE_PATH} ${LOCAL_CHART_REMOTE_COMMIT_ID} HEAD^ -- ${{ env.REMOTE_CHART_ROOT_PATH }}
                  echo
                  
                  # Apply patch
                  cd ${GITHUB_WORKSPACE}
                  pwd; echo

                  git apply \
                    -p $(awk -F '/' '{ print NF-0 }' <<< $(sed -r 's|/$||' <<< ${{ env.REMOTE_CHART_ROOT_PATH }})) \
                    --index --check --stat --apply --allow-empty --verbose \
                    --directory ${{ env.LOCAL_CHART_ROOT_PATH }} \
                    ${PATCH_FILE_PATH}
              fi
          fi

          echo
          echo CREATE_PULL_REQUEST="true" >> $GITHUB_ENV
          echo PR_TITLE="[Sync] Update ${{ env.CHART_NAME }} (version ${{ env.REMOTE_CHART_VERSION }})" >> $GITHUB_ENV
          echo PR_AUTHOR="${{ env.ORIGINAL_COMMIT_AUTHOR_NAME }} <${{ env.ORIGINAL_COMMIT_AUTHOR_EMAIL }}>" >> $GITHUB_ENV


      # Update chart dependency version
      - name: Update chart dependency version
        if: env.REMOTE_CHART_VERSION != env.LOCAL_CHART_VERSION && env.CHART_SYNC_TYPE == 'dependency'
        run: |
          if [ -f "${{ env.LOCAL_CHART_ROOT_PATH }}/Chart.yaml" ]; then
              yq eval -i '.dependencies |= map(select(.name == "${{ env.REMOTE_CHART_NAME }}").version = "${{ env.REMOTE_CHART_VERSION }}")' ${{ env.LOCAL_CHART_ROOT_PATH }}/Chart.yaml

              echo
              echo CREATE_PULL_REQUEST="true" >> $GITHUB_ENV
              echo PR_TITLE="[Sync] Update ${{ env.CHART_NAME }} dependency (version ${{ env.REMOTE_CHART_VERSION }})" >> $GITHUB_ENV
              echo PR_AUTHOR="${GITHUB_ACTOR} <${GITHUB_ACTOR}@users.noreply.github.com>" >> $GITHUB_ENV
          fi


      # Update chart metadata
      - name: Update chart metadata
        if: env.REMOTE_CHART_VERSION != env.LOCAL_CHART_VERSION && env.CREATE_PULL_REQUEST == 'true'
        run: |
          if [ "$(yq eval '.dependencies' ${{ env.LOCAL_CHART_ROOT_PATH }}/Chart.yaml)" != "null" ]; then
              for HELM_CHART_DEPENDENCY_REPOSITORY in $(yq eval '.dependencies[].repository' ${{ env.LOCAL_CHART_ROOT_PATH }}/Chart.yaml); do
                  if [ -z "$(grep -E '^file://' <<< ${HELM_CHART_DEPENDENCY_REPOSITORY})" ]; then
                      echo
                      helm repo add "$(cut -d '/' -f 3 <<< ${HELM_CHART_DEPENDENCY_REPOSITORY})" ${HELM_CHART_DEPENDENCY_REPOSITORY} --debug
                  fi
              done

              echo
              cd ${{ env.LOCAL_CHART_ROOT_PATH }}; pwd

              echo
              helm dependency update --debug
          fi

          yq eval -i '.description = "'${{ env.REMOTE_CHART_DESCRIPTION }}'"' ${{ env.LOCAL_CHART_ROOT_PATH }}/Chart.yaml
          yq eval -i '.appVersion = "'${{ env.REMOTE_CHART_APPVERSION }}'"' ${{ env.LOCAL_CHART_ROOT_PATH }}/Chart.yaml


      # Create Pull Request
      - name: Create Pull Request
        id: createPullRequest
        if: env.REMOTE_CHART_VERSION != env.LOCAL_CHART_VERSION && env.CREATE_PULL_REQUEST == 'true'
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.PAT_PUBLIC_MGR }}
          title: ${{ env.PR_TITLE }}
          body: |
            ## Original commit log
            <br/>

            > commit [${{ env.ORIGINAL_COMMIT_ID }}][1]
            >
            > Author: [${{ env.ORIGINAL_COMMIT_AUTHOR_NAME }}](mailto:${{ env.ORIGINAL_COMMIT_AUTHOR_EMAIL }})
            >
            > Date: &nbsp;&nbsp;&nbsp;${{ env.ORIGINAL_COMMIT_DATE }}
            >
            > &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;${{ env.ORIGINAL_COMMIT_MESSAGE }}
            
            [1]: ${{ env.ORIGINAL_COMMIT_URL }}
          labels: |
            automated
            sync
            ${{ env.CHART_NAME }}
          commit-message: Sync ${{ env.CHART_NAME }} version ${{ env.REMOTE_CHART_VERSION }} [${{ env.ORIGINAL_COMMIT_ID }}]
          author: ${{ env.PR_AUTHOR }}
          signoff: false
          assignees: ${GITHUB_ACTOR}
          base: ${{ env.PR_BASE_BRANCH }}
          branch: sync-pr/${{ env.CHART_NAME }}
          branch-suffix: short-commit-hash
          delete-branch: true
      

      # Enable Automerge
      - name: Enable Automerge
        if: steps.createPullRequest.outputs.pull-request-operation == 'created'
        uses: peter-evans/enable-pull-request-automerge@v1
        with:
          token: ${{ secrets.PAT_PUBLIC_MGR }}
          pull-request-number: ${{ steps.createPullRequest.outputs.pull-request-number }}
          merge-method: squash