name: Test Helm chart
  
on: pull_request

env:
  HELM_CHART_BASE_PATH: charts
  

jobs:
  test_helm_chart:

    runs-on: ubuntu-latest

    outputs: {}
    
    name: Test Helm chart
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      

      - name: Set up Helm
        uses: azure/setup-helm@v1


      - name: Set up YQ
        uses: chrisdickinson/setup-yq@latest
        with:
          yq-version: v4.16.2
      

      - name: Lint changed charts
        run: |
          echo ":: git log"
          git log --stat --pretty=format: -n 1 -- ${{ env.HELM_CHART_BASE_PATH }}
          echo
          git log --name-only --pretty=format: -n 1 -- ${{ env.HELM_CHART_BASE_PATH }}
          
          echo
          echo ":: helm lint"
          # find $(git log --name-only --pretty=format: -n 1 -- ${{ env.HELM_CHART_BASE_PATH }}) -name "Chart.yaml" | xargs dirname | xargs helm lint
          
          for HELM_CHART_FILE_PATH in $(find $(git log --name-only --pretty=format: -n 1 -- ${{ env.HELM_CHART_BASE_PATH }}) -name "Chart.yaml"); do
              echo
              cd $(${HELM_CHART_FILE_PATH} | dirname)
              pwd

              if [ "$(yq eval '.dependencies' ${HELM_CHART_FILE_PATH})" != "null" ]; then
                  for HELM_CHART_DEPENDENCY_REPOSITORY in "$(yq eval '.dependencies[].repository' ${HELM_CHART_FILE_PATH})"; do
                      if [ -z "$(grep -E '^file://' <<< ${HELM_CHART_DEPENDENCY_REPOSITORY})" ]; then
                          helm repo add "$(cut -d '/' -f 3 <<< ${HELM_CHART_DEPENDENCY_REPOSITORY})" ${HELM_CHART_DEPENDENCY_REPOSITORY}
                          echo
                      fi
                  done

                  echo
                  helm repo update

                  echo
                  helm dependency update
              fi

              helm lint .
          done

          exit 1