name: Test Helm chart
  
on: pull_request

env:
  HELM_CHARTS_ROOT_PATH: charts
  

jobs:
  test_helm_chart:

    runs-on: ubuntu-latest

    outputs: {}
    
    name: Test Helm chart
    steps:
      - uses: actions/checkout@v2

      - name: Set up Helm
        uses: azure/setup-helm@v1
      
      - name: Lint changed charts
        run: |
          echo ":: git status"
          git status
          echo
          echo ":: git diff-tree stats"
          git diff-tree --no-commit-id --stat -r ${GITHUB_SHA} -- ${{ env.HELM_CHARTS_ROOT_PATH }}
          echo "name-only"
          git diff-tree --no-commit-id --name-only -r $(git rev-parse HEAD) -- ${{ env.HELM_CHARTS_ROOT_PATH }}
          echo "find"
          find $(git diff-tree --no-commit-id --name-only -r $(git rev-parse HEAD) -- ${{ env.HELM_CHARTS_ROOT_PATH }} | xargs dirname)
          echo
          echo ":: helm lint"
          find $(git diff-tree --no-commit-id --name-only -r ${GITHUB_SHA} -- ${{ env.HELM_CHARTS_ROOT_PATH }} | xargs dirname) -name "Chart.yaml" | \
          uniq | \
          xargs helm lint