name: Test Helm chart
  
on: pull_request

env:
  HELM_CHARTS_ROOT_PATH: charts
  

jobs:
  test_helm_chart:

    runs-on: ubuntu-latest

    outputs: {}
    
    name: Test Helm chart
    steps:
      - uses: actions/checkout@v2

      - name: Set up Helm
        uses: azure/setup-helm@v1
      
      - name: Lint changed charts
        run: |
          echo ":: git log"
          git log --stat --pretty=format: -n 1 -- ${{ env.HELM_CHARTS_ROOT_PATH }}
          echo
          git log --name-only --pretty=format: -n 1 -- ${{ env.HELM_CHARTS_ROOT_PATH }}
          
          echo
          echo ":: helm lint"
          # find $(git log --name-only --pretty=format: -n 1 -- ${{ env.HELM_CHARTS_ROOT_PATH }}) -name "Chart.yaml" | xargs dirname | xargs helm lint
          
          git branch -a

          git log --name-only --pretty=format:"%B" -- ${{ env.HELM_CHARTS_ROOT_PATH }}


          exit 1