name: Test Helm charts
  
on: pull_request

env:
  GIT_REMOTE: origin
  GIT_REMOTE_TARGET_BRANCH: main
  HELM_CHARTS_ROOT_PATH: charts
  

jobs:
  test_helm_charts:

    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Set up Helm
        uses: azure/setup-helm@v1
      
      # - name: Lint changed charts
      #   run: |
      #     git log --name-status -n 1
      #     echo ""
      #     git log --name-only --pretty=format: -n 1 -- ${{ env.HELM_CHARTS_ROOT_PATH }} | find -name "Chart.yaml" | xargs dirname | xargs helm lint

      - name: Lint changed charts
        run: |
          git status
          echo ""
          git branch -a
          echo ""
          git diff --stat ${{ env.GIT_REMOTE }}/${{ env.GIT_REMOTE_TARGET_BRANCH }} -- ${{ env.HELM_CHARTS_ROOT_PATH }}
          echo ""
          git diff --name-only ${{ env.GIT_REMOTE }}/${{ env.GIT_REMOTE_TARGET_BRANCH }} -- ${{ env.HELM_CHARTS_ROOT_PATH }} | find -name "Chart.yaml" | xargs dirname | xargs helm lint

    
