{
 "title": "Application / Overview",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_namespace_created,namespace)"
    }
   },
   {
    "name": "app_instance",
    "label": "App. instance",
    "query": {
     "query": "label_values(kube_pod_info{namespace=~\"$namespace\"},created_by_name)"
    }
   },
   {
    "name": "container",
    "label": "Container",
    "query": {
     "query": "label_values(kube_pod_container_info{namespace=\"$namespace\", pod=~\"$app_instance.*\"},container)"
    }
   },
   {
    "name": "device",
    "query": {
     "query": "label_values(container_fs_reads_bytes_total{container=~\"$container\", pod=~\"$app_instance.*\", device!~\"/dev/dm-.*\"},device)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Realtime statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "DataSource",
   "targets": [
    {}
   ]
  },
  {
   "title": "Mem Usage Statistics",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{pod=~\"$app_instance.*\",container!=\"\"})",
     "legendFormat": "Usage"
    },
    {
     "expr": "sum(container_memory_rss{pod=~\"$app_instance.*\",container!=\"\"})",
     "legendFormat": "RSS"
    },
    {
     "expr": "sum(container_memory_cache{pod=~\"$app_instance.*\",container!=\"\"})",
     "legendFormat": "Cache"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{pod=~\"$app_instance.*\",container!=\"\"})",
     "legendFormat": "Working"
    }
   ]
  },
  {
   "title": "load [5m]",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{pod=~\"$app_instance.*\",container!=\"\"}[5m]))"
    }
   ]
  },
  {
   "title": "CPU Quota",
   "type": "table",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{pod=~\"$app_instance.*\",unit=\"core\"})",
     "legendFormat": "request"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{pod=~\"$app_instance.*\",unit=\"core\"})",
     "legendFormat": "limit"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_fs_reads_bytes_total{pod=~\"$app_instance.*\",container!=\"\",device!~\"/dev/dm-.*\"})by(device) > 0",
     "legendFormat": "{{device}}: read"
    },
    {
     "expr": "sum(container_fs_writes_bytes_total{pod=~\"$app_instance.*\",container!=\"\",device!~\"/dev/dm-.*\"})by(device) > 0",
     "legendFormat": "{{device}}: wirte"
    }
   ]
  },
  {
   "title": "transmit_rate [5m]",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{pod=~\"$app_instance.*\",interface=\"eth0\"}[5m]))by(container)"
    }
   ]
  },
  {
   "title": "receive_rate [5m]",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_bytes_total{pod=~\"$app_instance.*\",interface=\"eth0\"}[5m]))by(container)"
    }
   ]
  },
  {
   "title": "CPU Usage Statistics",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(irate(container_cpu_usage_seconds_total{pod=~\"$app_instance.*\",container!=\"\"}[5m]))by(container) > 0",
     "legendFormat": "{{container}}"
    },
    {
     "expr": "max(kube_pod_container_resource_requests{pod=~\"$app_instance.*\",container!=\"\",unit=\"core\"})",
     "legendFormat": "request"
    },
    {
     "expr": "max(kube_pod_container_resource_limits{pod=~\"$app_instance.*\",container!=\"\",unit=\"core\"})",
     "legendFormat": "limit"
    }
   ]
  },
  {
   "title": "Network packet in/out [5m]",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_network_receive_packets_total{pod=~\"$app_instance.*\",interface=\"eth0\"}) > 0",
     "legendFormat": "receive: total"
    },
    {
     "expr": "sum(container_network_receive_errors_total{pod=~\"$app_instance.*\",interface=\"eth0\"}) > 0",
     "legendFormat": "receive: error"
    },
    {
     "expr": "sum(container_network_receive_packets_dropped_total{pod=~\"$app_instance.*\",interface=\"eth0\"}) > 0",
     "legendFormat": "receive: dropped"
    },
    {
     "expr": "sum(container_network_transmit_packets_total{pod=~\"$app_instance.*\",interface=\"eth0\"}) > 0",
     "legendFormat": "transmit: total"
    },
    {
     "expr": "sum(container_network_transmit_errors_total{pod=~\"$app_instance.*\",interface=\"eth0\"}) > 0",
     "legendFormat": "transmit: error"
    },
    {
     "expr": "sum(container_network_transmit_packets_dropped_total{pod=~\"$app_instance.*\",interface=\"eth0\"}) > 0",
     "legendFormat": "transmit: dropped"
    }
   ]
  },
  {
   "title": "Memory_failcnt",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_failcnt{pod=~\"$app_instance.*\",container!=\"\"})"
    }
   ]
  },
  {
   "title": "Memory_failures",
   "type": "table",
   "description": "\nThe following statistics are only available by kernels from 2.6 \npgfault     –  Number of page faults the system has made per second (minor + major)  \npgmajfault  –  Number of major faults per second the system required loading a memory page from disk",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg(increase(container_memory_failures_total{pod=~\"$app_instance.*\"}[10m]))",
     "legendFormat": "pgfault"
    },
    {
     "expr": "avg(increase(container_memory_failures_total{pod=~\"$app_instance.*\"}[10m]))",
     "legendFormat": "pgmajfault"
    }
   ]
  },
  {
   "title": "Disk R/W size",
   "type": "table",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_fs_reads_bytes_total{pod=~\"$app_instance.*\",device=~\"$device\",device!~\"/dev/dm-.*\"})",
     "legendFormat": "read_bytes"
    },
    {
     "expr": "sum(container_fs_writes_bytes_total{pod=~\"$app_instance.*\",device=~\"$device\",device!~\"/dev/dm-.*\"})",
     "legendFormat": "wirte_bytes"
    }
   ]
  },
  {
   "title": "disk io",
   "type": "table",
   "description": "当前I/O队列个数及请求等待时间",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } }
  },
  {
   "title": "Resource usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "irate(container_cpu_usage_seconds_total{pod=~\"$app_instance.*\",container=~\"$container\"}[5m])",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "max(kube_pod_container_resource_requests{pod=~\"$app_instance.*\",unit=\"core\"})",
     "legendFormat": "request"
    },
    {
     "expr": "max(kube_pod_container_resource_limits{pod=~\"$app_instance.*\",unit=\"core\"})",
     "legendFormat": "limit"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{pod=~\"$app_instance.*\",container=~\"$container\"}",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "max(kube_pod_container_resource_requests{pod=~\"$app_instance.*\",unit=\"byte\"})",
     "legendFormat": "request"
    },
    {
     "expr": "max(kube_pod_container_resource_limits{pod=~\"$app_instance.*\",unit=\"byte\"})",
     "legendFormat": "limit"
    }
   ]
  },
  {
   "title": "Network [5m]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{pod=~\"$app_instance.*\"}[5m]))by(pod)",
     "legendFormat": "{{pod}} - transmit"
    },
    {
     "expr": "sum(irate(container_network_receive_bytes_total{pod=~\"$app_instance.*\"}[5m]))by(pod)",
     "legendFormat": "{{pod}} - receive"
    }
   ]
  },
  {
   "title": "Disk R/W rate [5m]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(irate(container_fs_reads_bytes_total{pod=~\"$app_instance.*\",device=~\"$device\",device!~\"/dev/dm-.*\"}[5m]))by(pod,device) > 0",
     "legendFormat": "{{pod}} - read"
    },
    {
     "expr": "sum(irate(container_fs_writes_bytes_total{pod=~\"$app_instance.*\",device=~\"$device\",device!~\"/dev/dm-.*\"}[5m]))by(pod,device) > 0",
     "legendFormat": "{{pod}} - write"
    }
   ]
  },
  {
   "title": "Disk R/W iops [5m]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "sum(irate(container_fs_reads_total{pod=~\"$app_instance.*\",device=~\"$device\",device!~\"/dev/dm-.*\"}[5m]))by(pod,device) > 0",
     "legendFormat": "{{pod}} - {{device}}: read_iops"
    },
    {
     "expr": "sum(irate(container_fs_writes_total{pod=~\"$app_instance.*\",device=~\"$device\",device!~\"/dev/dm-.*\"}[5m]))by(pod,device) > 0",
     "legendFormat": "{{pod}} - {{device}}: write_iops"
    }
   ]
  },
  {
   "title": "Disk IO time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(irate(container_fs_write_seconds_total{pod=~\"$app_instance.*\",device=~\"$device\"}[2m]))by(pod,device)",
     "legendFormat": "{{pod}} - {{device}}: write_iops"
    },
    {
     "expr": "sum(irate(container_fs_read_seconds_total{pod=~\"$app_instance.*\",device=~\"$device\"}[2m]))by(pod,device)",
     "legendFormat": "{{pod}} - {{device}}: read_iops"
    }
   ]
  }
 ]
}